### ISSUE TITLE
`persistence.external.core.write_objects ` write long length currency_pairs, get error:  pyarrow.lib.ArrowInvalid

### ISSUE THREAD

**Issue by gnemoug** [nautechsystems/nautilus_trader#1010] opened 2023-02-17 23:40 UTC
# Bug Report

### Expected Behavior
I use `BinanceSpotInstrumentProvider` fetch 2000+ CurrencyPairs, when I use `write_objects` to save 300 of them, it works successfully;  but if I use `write_objects` to save all of  them in the catalog will get error.

### Actual Behavior
Got error: 

> ../../opt/miniconda3/envs/nautilus_catalog/lib/python3.10/site-packages/nautilus_trader/persistence/external/core.py:362: in write_objects
>     write_tables(catalog=catalog, tables=tables, **kwargs)
> ../../opt/miniconda3/envs/nautilus_catalog/lib/python3.10/site-packages/nautilus_trader/persistence/external/core.py:249: in write_tables
>     write_parquet(
> ../../opt/miniconda3/envs/nautilus_catalog/lib/python3.10/site-packages/nautilus_trader/persistence/external/core.py:293: in write_parquet
>     table = pa.Table.from_pandas(df, schema=schema)
> pyarrow/table.pxi:3490: in pyarrow.lib.Table.from_pandas
>     ???
> pyarrow/table.pxi:3575: in pyarrow.lib.Table.from_arrays
>     ???
> pyarrow/table.pxi:1398: in pyarrow.lib._sanitize_arrays
>     ???
> pyarrow/array.pxi:347: in pyarrow.lib.asarray
>     ???
> pyarrow/array.pxi:926: in pyarrow.lib.Array.cast
>     ???
> ../../opt/miniconda3/envs/nautilus_catalog/lib/python3.10/site-packages/pyarrow/compute.py:389: in cast
>     return call_function("cast", [arr], options)
> pyarrow/_compute.pyx:560: in pyarrow._compute.call_function
>     ???
> pyarrow/_compute.pyx:355: in pyarrow._compute.Function.call
>     ???
> pyarrow/error.pxi:144: in pyarrow.lib.pyarrow_internal_check_status
>     ???
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> E   pyarrow.lib.ArrowInvalid: Integer value 128 not in range: -128 to 127
> 
> pyarrow/error.pxi:100: ArrowInvalid

### Steps to Reproduce the Problem

1. Use `BinanceSpotInstrumentProvider` fetch live 2000+ spot currency_pairs
2. Setup `ParquetDataCatalog`
3. Use `write_objects` save all the spot currency_pairs

### Specifications

- OS platform: MacOs
- Python version: Python 3.10
- `nautilus_trader` version: 1.168.0

**Comment by cjdsellers** [comment] 2023-02-18 04:33
This is very likely caused by the use of `int8` for currency indexes in the schema (see [serialization/arrow/schema.py](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/serialization/arrow/schema.py#L568)).

The schemas will very likely be changed with the introduction of catalog v2, there's an argument for modifying now though to lift these restrictions you're running into, although this will potentially break the current catalogs schema layout.

Thoughts @limx0 ?

**Comment by limx0** [comment] 2023-02-18 04:35
I think int8 -> int16 is a safe change.

**Comment by cjdsellers** [comment] 2023-02-18 05:45
@gnemoug I've pushed some changes to the `develop` branch. If you could test that out, there is a high change that limitation is now fixed.

**Comment by cjdsellers** [comment] 2023-02-18 20:56
> Is there a roadmap about the catalog v2, current catalog is powerful but confused!

Its currently a top priority, and you should see a lot of activity over the next few weeks!

Closing this as now resolved.

**Closed by cjdsellers** 2023-02-18 20:56 UTC
Labels: bug
