### ISSUE TITLE
WebSocketClient does not start after reconnect

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#1090] opened 2023-04-27 02:21 UTC
# Bug Report
Looks like ``WebSocketClient`` does not call `start` when reconnecting. I think this change is needed at the cython level due to unwritable C properties in python. Also it would be nice if the aiohttp session was properly closed before calling `_session.ws_connect` because aiohttp complains with an "Unclosed client session" message.

### Expected Behavior
After reconnecting, the websocket client `is_running` property resets to True and messages are again handled forever.

### Actual Behavior
After reconnecting, the websocket client `is_running` property does not reset to True and messages are not handled thereafter.

### Steps to Reproduce the Problem

1. Start a websocket client 
2. Disconnect the websocket client (`await client.disconnect()`)
3. Reconnect the websocket client (`await client.reconnect()`)

### Specifications

- OS platform: macOS 13.3.1
- Python version: 3.10.8
- `nautilus_trader` version: 1.171.0

**Comment by cjdsellers** [comment] 2023-04-27 09:29
Hi @miller-moore 

Thanks for the report here.

So actually the `reconnect` method doesn't need to be called again if the `start` task is already running.

To prove the invariant I've added an extra condition to the `reconnect` method that if the websocket is not running then to create a new `start` task:

```
        if not self.is_running:
            # Create a new `start` task
            self._task = self._loop.create_task(self.start())
        self._log.debug("WebSocket reconnected.")
        await self.post_reconnection()
```
When I did add calling `start` into the reconnect, there was the following error (start was already running):
```
RuntimeError: Concurrent call to receive() is not allowed
```

I've also added a test covering your disconnect and reconnect case.

Additionally we're cleanly closing the session on disconnect, which we're now doing:
```
        if self._session is not None and not self._session.closed:
            await self._session.close()
        self._log.debug("WebSocket closed.")
```

Please let me know if this fixes the "Unclosed client session" message.

Now pushed to `develop` branch.

**Closed by cjdsellers** 2023-04-27 09:29 UTC
Labels: bug

**Comment by miller-moore** [comment] 2023-04-27 11:01
I am referring specifically to the behavior that occurs _after calling `disconnect`_. Is the meaning of `reconnect` not “connect and start” after a disconnection?

**Comment by miller-moore** [comment] 2023-04-27 11:07
Additionally, instead of closing `_session` to avoid the previously stated aiohttp message (since it is already closed if `disconnect` has been called), I believe it needs to be reinstantiated. This could be accomplished easily if `ws_kwargs` are cached when `connect` is first called.

**Comment by cjdsellers** [comment] 2023-04-27 11:08
Indeed, and this is specifically what was covered above.

> Looks like WebSocketClient does not call start when reconnecting
This is because the websocket is already running, the `start` task is still active.

Please provide any logs where the websocket isn't behaving as intended (i.e. upon reconnect) and I have have a look.

**Comment by cjdsellers** [comment] 2023-04-27 11:09
> Additionally, instead of closing `_session` to avoid the previously stated aiohttp message (since it is already closed if `disconnect` has been called), I believe it needs to be reinstantiated. This could be accomplished easily if `ws_kwargs` are cached when `connect` is first called.

So something like the new implementation?

```
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(loop=self._loop)
```

**Comment by miller-moore** [comment] 2023-04-27 11:13
> This is because the websocket is already running, the start task is still active.

My particular point seems to be missed again. _After calling `disconnect`_, the client _is in fact not running_.

**Comment by miller-moore** [comment] 2023-04-27 11:15
> > Additionally, instead of closing `_session` to avoid the previously stated aiohttp message (since it is already closed if `disconnect` has been called), I believe it needs to be reinstantiated. This could be accomplished easily if `ws_kwargs` are cached when `connect` is first called.
> 
> So something like the new implementation?
> 
> ```
>         if self._session is None or self._session.closed:
>             self._session = aiohttp.ClientSession(loop=self._loop)
> ```

Yes I think that would do it.

**Comment by cjdsellers** [comment] 2023-04-27 11:16
```
    async def reconnect(self) -> None:
        """
        Reconnect the WebSocket client session.

        Will call `post_reconnection()` following connection.

        """
        self._log.debug(f"Reconnecting WebSocket to {self._ws_url}")

        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(loop=self._loop)
        self._ws = await self._session.ws_connect(url=self._ws_url, **self._ws_kwargs)
        if not self.is_running:  # <-------------------- we now call start on reconnect if not running
            # Create a new `start` task
            await self.close()
            self._task = self._loop.create_task(self.start())
        self._log.debug("WebSocket reconnected.")
        await self.post_reconnection()
        self.is_connected = True
        self.is_stopping = False
```

Please provide any logs where the websocket isn't behaving as intended (i.e. upon reconnect) and I can have a look.

**Comment by miller-moore** [comment] 2023-04-27 11:19
Ok that looks great. To what branch has this change been committed? I’ll give it a try, but I do not expect any problems per the code above

**Comment by cjdsellers** [comment] 2023-04-27 11:20
> 
> Now pushed to `develop` branch.
