### ISSUE TITLE
Currency_type issue

### ISSUE THREAD

**Issue by DownBadCapital** [nautechsystems/nautilus_trader#755] opened 2022-09-02 21:25 UTC
# Bug Report

I'm creating a new currency with

```
> `def create_currency (ticker):
>     if Currency.from_str(ticker) is None:
>         return Currency(
>             code = ticker,
>             precision=8,
>             iso4217=0,
>             name=ticker,
>             currency_type=CurrencyType.CRYPTO,
>         )
>     Currency.register(currency=Currency.from_str(ticker),overwrite=False)`
> 
```

I'm still ultimately getting

```
> `Currency 'LPT' not found, created Currency { code: "LPT", precision: 8, iso4217: 0, name: "LPT", currency_type: Fiat }
> Currency 'LPT' not found, created Currency { code: "LPT", precision: 8, iso4217: 0, name: "LPT", currency_type: Fiat }`
```

It doesn't appear to cause any immediate issues, but the currency_type param doesn't appear to work as expected. That, or, it's creating a duplicate fiat version simultaneously. If I query if the currency exists and is crypto, it returns TRUE. So not clear what the issue is, but wanted to raise.

**Comment by cjdsellers** [comment] 2022-09-02 22:12
Thanks for the report!

Can you confirm what the value of `ticker` is in your above example? I think we both expect this to be `'LPT'`

Two questions:
- When are you running the first creation code snippet?
- When do you see the prints that a currency was created?

**Comment by cjdsellers** [comment] 2022-09-02 22:25
I found on the Rust side `CurrencyType` is the only enum which doesn't explicitly assign an integer value to the variants (which I've now done), so that may have been the source of the Fiat vs Crypto bug.

**Comment by cjdsellers** [comment] 2022-09-03 12:47
@DownBadCapital Let me know if this issue persists on `develop` when you can

**Comment by cjdsellers** [comment] 2022-09-11 10:37
Closing as unable to reproduce and enum implementations appear in line.

**Closed by cjdsellers** 2022-09-11 10:37 UTC
Labels: bug
