### ISSUE TITLE
Slippage Error on Order Filled

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1031] opened 2023-03-02 07:52 UTC
# Bug Report
When placing `TrailingStopMarketOrder` with `trigger_price=None` upon Order fill produced below exception. As per doc `trigger_price` is Optional, or is it mandatory field?

```
2023-03-02T07:16:02.525227900Z [INF] TESTER-001.MyTestStrategy-001: <--[EVT] OrderInitialized(instrument_id=GBP/USD.IDEALPRO, client_order_id=O-20230302-001-001-1, side=SELL, type=LIMIT, quantity=100_000.0, time_in_force=GTD, post_only=False, reduce_only=False, options={'price': '1.19770', 'display_qty': None, 'expire_time_ns': 1677741662524553100}, emulation_trigger=NO_TRIGGER, contingency_type=OTO, order_list_id=OL-20230302-001-001-1, linked_order_ids=['O-20230302-001-001-2'], parent_order_id=None, tags=None).
2023-03-02T07:16:02.525254800Z [INF] TESTER-001.MyTestStrategy-001: <--[EVT] OrderInitialized(instrument_id=GBP/USD.IDEALPRO, client_order_id=O-20230302-001-001-2, side=BUY, type=TRAILING_STOP_MARKET, quantity=100_000.0, time_in_force=GTC, post_only=False, reduce_only=False, options={'trigger_price': None, 'trigger_type': 'DEFAULT', 'trailing_offset': '0.00080', 'trailing_offset_type': 'PRICE', 'expire_time_ns': 0}, emulation_trigger=NO_TRIGGER, contingency_type=NO_CONTINGENCY, order_list_id=OL-20230302-001-001-1, linked_order_ids=None, parent_order_id=O-20230302-001-001-1, tags=None).
2023-03-02T07:16:02.525347900Z [DBG] TESTER-001.Cache: Added OrderList(id=OL-20230302-001-001-1, instrument_id=GBP/USD.IDEALPRO, strategy_id=MyTestStrategy-001, orders=[LimitOrder(SELL 100_000.0 GBP/USD.IDEALPRO LIMIT @ 1.19770 GTD 2023-03-02T07:21:02.524Z, status=INITIALIZED, client_order_id=O-20230302-001-001-1, venue_order_id=None, contingency_type=OTO, linked_order_ids=[O-20230302-001-001-2], tags=None), TrailingStopMarketOrder(BUY 100_000.0 GBP/USD.IDEALPRO TRAILING_STOP_MARKET[DEFAULT] 0.00080-TRAILING_OFFSET[PRICE] GTC, status=INITIALIZED, client_order_id=O-20230302-001-001-2, venue_order_id=None, parent_order_id=O-20230302-001-001-1, tags=None)]).
2023-03-02T07:16:02.525400200Z [DBG] TESTER-001.Cache: Added LimitOrder(SELL 100_000.0 GBP/USD.IDEALPRO LIMIT @ 1.19770 GTD 2023-03-02T07:21:02.524Z, status=INITIALIZED, client_order_id=O-20230302-001-001-1, venue_order_id=None, contingency_type=OTO, linked_order_ids=[O-20230302-001-001-2], tags=None).
2023-03-02T07:16:02.525416700Z [DBG] TESTER-001.Cache: Added TrailingStopMarketOrder(BUY 100_000.0 GBP/USD.IDEALPRO TRAILING_STOP_MARKET[DEFAULT] 0.00080-TRAILING_OFFSET[PRICE] GTC, status=INITIALIZED, client_order_id=O-20230302-001-001-2, venue_order_id=None, parent_order_id=O-20230302-001-001-1, tags=None).
2023-03-02T07:16:02.525496200Z [DBG] TESTER-001.Cache: Added command SubmitOrderList(order_list=OrderList(id=OL-20230302-001-001-1, instrument_id=GBP/USD.IDEALPRO, strategy_id=MyTestStrategy-001, orders=[LimitOrder(SELL 100_000.0 GBP/USD.IDEALPRO LIMIT @ 1.19770 GTD 2023-03-02T07:21:02.524Z, status=INITIALIZED, client_order_id=O-20230302-001-001-1, venue_order_id=None, contingency_type=OTO, linked_order_ids=[O-20230302-001-001-2], tags=None), TrailingStopMarketOrder(BUY 100_000.0 GBP/USD.IDEALPRO TRAILING_STOP_MARKET[DEFAULT] 0.00080-TRAILING_OFFSET[PRICE] GTC, status=INITIALIZED, client_order_id=O-20230302-001-001-2, venue_order_id=None, parent_order_id=O-20230302-001-001-1, tags=None)]), position_id=None, exec_algorithm_specs=None)
2023-03-02T07:16:02.525547800Z [INF] TESTER-001.MyTestStrategy-001: [CMD]--> SubmitOrderList(order_list=OrderList(id=OL-20230302-001-001-1, instrument_id=GBP/USD.IDEALPRO, strategy_id=MyTestStrategy-001, orders=[LimitOrder(SELL 100_000.0 GBP/USD.IDEALPRO LIMIT @ 1.19770 GTD 2023-03-02T07:21:02.524Z, status=INITIALIZED, client_order_id=O-20230302-001-001-1, venue_order_id=None, contingency_type=OTO, linked_order_ids=[O-20230302-001-001-2], tags=None), TrailingStopMarketOrder(BUY 100_000.0 GBP/USD.IDEALPRO TRAILING_STOP_MARKET[DEFAULT] 0.00080-TRAILING_OFFSET[PRICE] GTC, status=INITIALIZED, client_order_id=O-20230302-001-001-2, venue_order_id=None, parent_order_id=O-20230302-001-001-1, tags=None)]), position_id=None, exec_algorithm_specs=None).
2023-03-02T07:16:03.017796900Z [INF] TESTER-001.MyTestStrategy-001: <--[EVT] OrderAccepted(instrument_id=GBP/USD.IDEALPRO, client_order_id=O-20230302-001-001-2, venue_order_id=423, account_id=InteractiveBrokers-DU2560712, ts_event=1677741363017321700).
2023-03-02T07:29:51.412281800Z [INF] TESTER-001.InteractiveBrokersClient-002: ANSWER orderStatus {'order_id': 423, 'status': 'Filled', 'filled': Decimal('100000'), 'remaining': Decimal('0'), 'avg_fill_price': 1.19709, 'perm_id': 1096798675, 'parent_id': 422, 'last_fill_price': 1.19709, 'client_id': 2, 'why_held': '', 'mkt_cap_price': 0.0}
File "nautilus_trader\\live\\execution_engine.pyx", line 349, in _run_evt_queue
File "nautilus_trader\\execution\\engine.pyx", line 625, in nautilus_trader.execution.engine.ExecutionEngine._handle_event
File "nautilus_trader\\execution\\engine.pyx", line 679, in nautilus_trader.execution.engine.ExecutionEngine._apply_event_to_order
File "nautilus_trader\\model\\orders\\base.pyx", line 865, in nautilus_trader.model.orders.base.Order.apply
File "nautilus_trader\\model\\orders\\base.pyx", line 926, in nautilus_trader.model.orders.base.Order._filled
File "nautilus_trader\\model\\orders\\trailing_stop_market.pyx", line 206, in nautilus_trader.model.orders.trailing_stop_market.TrailingStopMarketOrder._set_slippage
AttributeError: 'NoneType' object has no attribute 'as_f64_c'
```

### Steps to Reproduce the Problem

1. Set the `TrailingStopMarketOrder` with `trigger_price=None`
2. Place the order and upon fill shall produce

### Specifications

- OS platform: Win10
- Python version: 3.10.6
- `nautilus_trader` version: 1.170.0 (develop)

**Comment by cjdsellers** [comment] 2023-03-02 10:33
For this one, I think that as a backstop this attribute error shouldn't occur, so if no `trigger_price` is set when `_set_slippage` is called then it immediately returns (effectively keeping slippage set to zero).

I think if there is no trigger price for a `TrailingStop*` type order, then the IB adapter should update it based on order acceptance with a trailing offset?

**Comment by rsmb7z** [comment] 2023-03-02 10:43
> For this one, I think that as a backstop this attribute error shouldn't occur, so if no `trigger_price` is set when `_set_slippage` is called then it immediately returns (effectively keeping slippage set to zero).

Agreed.



> I think if there is no trigger price for a `TrailingStop*` type order, then the IB adapter should update it based on order acceptance with a trailing offset?

Yes this happened while playing to see what happens TriggerPrice is set to None. So as for the IB, order went through as with offset value and operates similar what Nautilus is intended in case of `None` i.e. *If ``None`` then will typically default
        to the delta of market price and `trailing_offset`*.

**Comment by cjdsellers** [comment] 2023-03-02 10:56
Fixed from 215cfdf6175eabc7758868061217c1e9bc12b67a.

**Comment by cjdsellers** [comment] 2023-03-02 10:57
> If `None` then will typically default to the delta of market price and `trailing_offset`

Exactly, so there _will_ be a price the order will trigger, and IB should provide this information as soon as the order is accepted I would think?

Closing this for now as the issue is fixed, but please continue with any thoughts.

**Closed by cjdsellers** 2023-03-02 10:57 UTC
Labels: bug

**Comment by rsmb7z** [comment] 2023-03-02 11:06
> Exactly, so there _will_ be a price the order will trigger, and IB should provide this information as soon as the order is accepted I would think?

Yes correct, on Order Fill event, `generate_order_filled` will be sent back to `ExecEngine`.

**Comment by cjdsellers** [comment] 2023-03-02 23:30
I think not even on fill, but on accepted. The actual trigger price in the market should be know if IB accept offset only (like Binance etc).

**Comment by rsmb7z** [comment] 2023-03-03 03:34
It doesn't send any pricing info on Accept. However we can set `trigger_price`.

**Comment by cjdsellers** [comment] 2023-03-03 06:13
That could be a good compromise to infer the initial trigger price based on some last look market price. When the order is finally filled though, is there a separate `stop_px` and `last_px`?

**Comment by rsmb7z** [comment] 2023-03-05 05:10
I don't think we get any such details. There are two classes which are return about Order:
- [OrderStatus](https://interactivebrokers.github.io/tws-api/interfaceIBApi_1_1EWrapper.html#a27ec36f07dff982f50968c8a8887d676): This we get as soon we place order and any frequent order status changes.
- [Execution](https://interactivebrokers.github.io/tws-api/classIBApi_1_1Execution.html): This is received when order is filled. Although filled event will be recieved in `OrderStatus` normally but `Execution` is recommended by IB more reliable and final.

The details about Order Submission described [here](https://interactivebrokers.github.io/tws-api/order_submission.html) gives some more details.

**Comment by cjdsellers** [comment] 2023-03-05 05:17
It looks like these might be the properties of the trailing stop with IB:
```
            Order order = new Order();
            order.Action = action;
            order.OrderType = "TRAIL";
            order.TotalQuantity = quantity;
            order.TrailingPercent = trailingPercent;
            order.TrailStopPrice = trailStopPrice;

```
We need the `TrailStopPrice` I think ASAP after order submit, and apply this to the Nautilus orders `trigger_price`, probably with an `OrderUpdated` event?

**Comment by rsmb7z** [comment] 2023-03-05 05:36
Yes correct but `Order` object is what we prepare and submit to IB and these are the fields supposed to be filled by us depending on `OrderType`. IB have only this one object for all type of Orders. Here is how I have implemented order tranformation:

https://github.com/rsmb7z/nautilus_trader/blob/ib_refactor/nautilus_trader/adapters/interactive_brokers/execution.py#L258
https://github.com/rsmb7z/nautilus_trader/blob/ib_refactor/nautilus_trader/adapters/interactive_brokers/parsing/execution.py#L68

**Comment by cjdsellers** [comment] 2023-03-05 05:43
Understood, and based on the trailing offset instruction, when the trigger price is updated with IB - do they emit an event about this?

**Comment by rsmb7z** [comment] 2023-03-05 05:55
Also there is unique 'OrderId' (int) we generate and attach to Order and that is what needed for any future Order operation. We don't have to convert the IB order back to Nautilus, we simply recreate and submit instruction with existing `OrderId` (thats how IB requires us to do).

Hence as I have added note, we should have option to add VenueOrderId at [Nautilus Submit Event](https://github.com/rsmb7z/nautilus_trader/blob/ib_refactor/nautilus_trader/adapters/interactive_brokers/execution.py#L456). Although IB generate `PermId` once order is accepted by their system but that's of no use in Nautilus perspective, because:

1. We cannot do anything with that any instruction we need are through original `OrderId` even if the program is restarted.
2. We have Nautilus `ClientOrderId` attached to `OrderRef` of IB field so we always know which Nautilus Order IB is sending update for.



> Understood, and based on the trailing offset instruction, when the trigger price is updated with IB - do they emit an event about this?

If Nautilus Order have the `trigger_price` it will attach to IB order `ib_order.trailStopPrice = order.trigger_price.as_double()`. By *updated with IB*, do you mean when the order is modified?

**Comment by cjdsellers** [comment] 2023-03-05 06:06
> If Nautilus Order have the trigger_price it will attach to IB order ib_order.trailStopPrice = order.trigger_price.as_double(). By updated with IB, do you mean when the order is modified?

I mean when the market moves and the orders trigger prices is modified on the IB side based on the trailing offset we provide, do they emit an event that the order has been updated?

My thinking here is, if we submit a trailing stop order to them with no trigger price, they will certainly assign one themselves on their system. We just need to determine when is the soonest we can get this information, and apply this to the Nautilus order (would fix this original slippage bug for example).

**Comment by rsmb7z** [comment] 2023-03-06 09:24
> My thinking here is, if we submit a trailing stop order to them with no trigger price, they will certainly assign one themselves on their system. We just need to determine when is the soonest we can get this information, and apply this to the Nautilus order (would fix this original slippage bug for example).

So in case we leave the `trailStopPrice (trigger_price)` empty, IB will simply assign `Current Price +/- auxPrice (trailing_offset)` precisely and there is no returning value. Let's hypothatically have two scenarios:

1. When `trigger_price` is entered and market moves fast in trigger direction, by the time IB received the Order it will immediately becomes Market Order because trigger conditions is True.
2. When `trigger_price` is left blank, market move doesn't matter as trigger price will get set once order is accepted by IB.

In both cases ExecutionDetail will have the filled price.
