### ISSUE TITLE
Rust OrderBookImbalance example strategy doesn't work

### ISSUE THREAD

**Issue by StephenLee2016** [nautechsystems/nautilus_trader#1971] opened 2024-09-28 13:39 UTC
Bug Report
one of the examples doesn't work
examples/live/binance/binance_spot_orderbook_imbalance_rust.py

Expected Behavior
Add here...

Actual Behavior
the error message reads as follow:

Traceback (most recent call last):
  File "/Users/nautilus_trader/examples/live/binance/binance_spot_orderbook_imbalance_rust.py", line 105, in <module>
    strategy = OrderBookImbalance(config=strat_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nautilus_trader/nautilus_trader/examples/strategies/orderbook_imbalance_rust.py", line 108, in __init__
    self.book = nautilus_pyo3.OrderBook(self.book_type, pyo3_instrument_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'instrument_id': 'BookType' object cannot be converted to 'InstrumentId'

Steps to Reproduce the Problem
pip install -U nautilus_trader
fill in my own api key and secret in binance_spot_orderbook_imbalance_rust.py
run the py file
Specifications
OS platform: Mac 13.4 M2
Python version: 3.11
nautilus_trader version: 1.203.0

**Comment by cjdsellers** [comment] 2024-09-29 10:22
Hi @StephenLee2016

Thanks for the report. This was caused by a param ordering change, now fixed on `develop` branch from commit aa12f5db01124e74612be439f1481d4e961e0bef.

**Closed by cjdsellers** 2024-09-29 10:22 UTC
Labels: bug
