### ISSUE TITLE
Cannot parse instruments well 

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#692] opened 2022-07-09 06:31 UTC
# Bug Report
(1)save instruments from binance_testnet
(2)using catalog.instruments(as_nautilus = True) to load instruments, CryptoPerpetual.info should parase well.
### Actual Behavior
meet this error:
` 
 File "/home/yang/nautilus_trader-develop/examples/catalog/tick2timebar.py", line 68, in <module>
    instrument = catalog.instruments(instrument_ids=[instrument_id],as_nautilus=True)
  File "/home/yang/nautilus_trader-develop/nautilus_trader/persistence/catalog/base.py", line 183, in instruments
    return self._query_subclasses(
  File "/home/yang/nautilus_trader-develop/nautilus_trader/persistence/catalog/parquet.py", line 198, in _query_subclasses
    df = self._query(
  File "/home/yang/nautilus_trader-develop/nautilus_trader/persistence/catalog/parquet.py", line 130, in _query
    return self._handle_table_nautilus(table=table, cls=cls, mappings=mappings)
  File "/home/yang/nautilus_trader-develop/nautilus_trader/persistence/catalog/parquet.py", line 178, in _handle_table_nautilus
    data = ParquetSerializer.deserialize(cls=cls, chunk=dicts)
  File "nautilus_trader/serialization/arrow/serializer.pyx", line 196, in nautilus_trader.serialization.arrow.serializer.ParquetSerializer.deserialize
  File "stringsource", line 69, in cfunc.to_py.__Pyx_CFunc_CryptoPerpetual__lParendict__rParen_to_py_6values.wrap
  File "nautilus_trader/model/instruments/crypto_perpetual.pyx", line 199, in nautilus_trader.model.instruments.crypto_perpetual.CryptoPerpetual.from_dict_c
TypeError: Expected bytes, got str`
### Steps to Reproduce the Problem
https://github.com/nautechsystems/nautilus_trader/discussions/505
### Specifications

- OS platform: Ubuntu 20.04 
- Python version:python 3.8 
- `nautilus_trader` version: latest develop 

My current solution is to replace crypto_perpetual.pyx L199 to:
`        cdef bytes  info= msgspec.json.encode(json.loads(values["info"]))`

**Comment by OnlyC** [comment] 2022-07-10 17:14
I'm getting the same error

**Comment by cjdsellers** [comment] 2022-07-12 04:52
This may have been caused by my recent change which standardized on `msgspec` and removed `orjson` as a dependency. I've noted your solution and will take another pass soon.

**Comment by cjdsellers** [comment] 2022-07-16 07:09
I found the issue. The arrow schema should use `pa.binary` for encoded JSON (bytes), so that those fields are stored as bytes and not strings (which `msgspec.json.decode` cannot handle).

Fixed on next push to `develop`

**Closed by cjdsellers** 2022-07-16 07:09 UTC
Labels: bug
