### ISSUE TITLE
Timer interrupts

### ISSUE THREAD

**Issue by cuberone** [nautechsystems/nautilus_trader#1357] opened 2023-11-19 16:55 UTC
# Bug Report

Timer `clock.set_timer` unexpectedly interrupts the loop when some iteration step takes a long time.

### Expected Behavior
The timer doesn't interrupt the loop.
Skip the next iteration step if required or start each iteration in a new thread.

### Actual Behavior
Timer stops without any log information.

### Steps to Reproduce the Problem
In a sample strategy put this code
   ```
 def on_start(self):
        self.num = 1
        self.clock.set_timer(
            name="test",
            stop_time=self.clock.utc_now() + pd.Timedelta(10, unit="s"),
            interval=pd.Timedelta(1, unit="s"),
            callback=self.test,
        )

    def test(self, event: TimeEvent) -> None:
        self.num = self.num + 1
        self.log.info(f"{self.num}")
        time.sleep(2)
```

Here it interrupts after the first loop.
But expected behaviour is to print 1,2,3,4,5,6,7,8,9,10 or 1,2,3,4,5

### Specifications

- OS platform: linux
- Python version: 3.10.12
- `nautilus_trader` version: 1.180.0

**Comment by cjdsellers** [comment] 2023-11-19 20:55
Hi @cuberone 

Thanks for your interest here.

So by design a trader instance is single threaded, which is one of the main things which allows the code parity between backtest and live. It also offers greater determinism and simplicity, we're only leverage threads outside the GIL right now to farm off blocking I/O operations. 

Because of this you must ensure that there are no blocking operations in any of your handler methods, including those which may be callbacks for timers.

To help with this there is also an executor available for actors and strategies, so that you can run your blocking code in a separate thread. Sadly I can't give you any docs or examples beyond the API reference at this point https://docs.nautilustrader.io/api_reference/common.html#module-nautilus_trader.common.executor.

Hope this helps!

Closing for now as the system isn't behaving out of spec here.

**Closed by cjdsellers** 2023-11-19 20:55 UTC
Labels: bug
