### ISSUE TITLE
Value error on large balance

### ISSUE THREAD

**Issue by DownBadCapital** [nautechsystems/nautilus_trader#885] opened 2022-12-02 18:54 UTC
# Bug Report

### Expected Behavior
Got this error today. Only occurs when I increase the starting cash of the backtest it seems. With 1 million USDT starting balance, the script runs for a few minutes until it hits a different error (ValueError: free amount was negative) which is not handled smoothly but is due to losses on trades. With 1 billion USDT starting balance, this error happens on the first trade:

### Actual Behavior

  File "nautilus_trader\\core\\correctness.pyx", line 57, in nautilus_trader.core.correctness.Condition.true
ValueError: `total` - `locked` != `free` amount

**Comment by cjdsellers** [comment] 2022-12-02 23:24
Hi @DownBadCapital 

Thanks for the report, there's also a similar open issue to improve these balance correctness checks.

Is this reproducible from any of the example backtest scripts?

**Comment by cjdsellers** [comment] 2022-12-03 05:46
Yes, we actually recently changes the path to the test data and this slipped through because there are currently no automated tests for this. Will fix it up shortly.

**Comment by DownBadCapital** [comment] 2022-12-04 00:33
Using 1.160.0 currently. You're saying that the examples work on develop branch? If so, I can update to that and see if this error still exists. If so, try to replicate in the examples.

**Comment by cjdsellers** [comment] 2022-12-04 00:55
Yes, so `develop` branch will work - the original balance calc error you're posting about likely still exists though

**Comment by cjdsellers** [comment] 2023-01-15 06:20
I just tried `crypto_ema_cross_ethusdt_trade_ticks.py` with `1_000_000_000 USDT` starting balance. I didn't see this error and may have fixed from a related bug.

Are you able to test or report if you still see this on latest `develop`?

**Comment by cjdsellers** [comment] 2023-01-20 22:38
I believe this may now be fixed from a related bug, and unable to reproduce myself.

Closing this for now.

**Closed by cjdsellers** 2023-01-20 22:38 UTC
Labels: bug
