### ISSUE TITLE
Randomize order of high/low ticks generated from bar data

### ISSUE THREAD

**Issue by tmorgan4** [nautechsystems/nautilus_trader#119] opened 2020-11-08 21:04 UTC
DISCALIMER: I'm filing these issues as I find them. Have a few more but trying to file one at a time. This was noticed in the master branch about 2 weeks (10/24/2020) ago so the code below is not completely up to date. Please disregard if this issue has already been resolved.

I haven't been able to fully identify the issue here but wanted to bring it to your attention. Some strange things are occurring in TickDataWrangler.pre_process() due to the way that zero-volume ticks are removed.

As an example, I added some extra debug prints using the included GBPUSD 1-minute data which is aggregated to create 3-minute bars. In some instances a tick may have zero-volume and gets removed. The bars created from these ticks do not seem to handle the removed ticks properly.

```
2020-10-24T08:21:59.562Z [WRN] BacktestEngine: 2008-01-01 04:49:00+00:00 Generating tick...
2020-10-24T08:21:59.562Z [WRN] BacktestEngine: 2008-01-01 04:49:00+00:00 Received tick ---> "GBP/USD.SIM,1.98500,1.98505,0,0,2008-01-01T04:49:59.900Z"
2020-10-24T08:21:59.562Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:49:59.900000+00:00"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98500,1.98505,0,0,2008-01-01T04:49:59.900Z"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:49:59.900000+00:00"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98488,1.98493,0,0,2008-01-01T04:49:59.900Z"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:49:59.900000+00:00"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:49:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98488,1.98493,24,24,2008-01-01T04:50:00.000Z"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:50:00+00:00 Advanced clock to tick.timestamp "2008-01-01 04:50:00+00:00"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:50:00+00:00 Generating tick...
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:50:00+00:00 Received tick ---> "GBP/USD.SIM,1.98495,1.98500,0,0,2008-01-01T04:51:59.900Z"
2020-10-24T08:21:59.563Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:51:59.900000+00:00"
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: Received GBP/USD.SIM-3-MINUTE-BID Bar(1.98505,1.98520,1.98488,1.98488,180,2008-01-01T04:51:00.000Z)
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: [CMD]--> SubmitOrder(venue=SIM, trader_id=BACKTESTER-000, account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-20, position_id=B-GBP/USD-10, strategy_id=EMACross-GBPUSD.
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderSubmitted(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-20, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderAccepted(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-20, order_id=B-GBP/USD-20, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderFilled(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-20, order_id=B-GBP/USD-20, position_id=B-GBP/USD-10, strategy_id=EMACross-GBPUSD, symbol=GBP/USD.SIM, side=SELL-TAKER, filled_qty=100,000, leaves_qty=0, avg_price=1.98495, commission=10.00 GBP, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] Portfolio: GBP/USD.SIM net position = 0
2008-01-01T04:51:59.900Z [INF] Portfolio: Updated SIM position maintenance margin to 0.00 USD
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] PositionClosed(account_id=SIM-000-SIMULATED, position_id=B-GBP/USD-10, strategy_id=EMACross-GBPUSD, entry=BUY, duration=00:03:59.900000, avg_open=1.98509, avg_close=1.98495, realized_points=-0.00014, realized_return=-0.007%, realized_pnl=2.95 GBP, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: [CMD]--> SubmitOrder(venue=SIM, trader_id=BACKTESTER-000, account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-21, position_id=NULL, strategy_id=EMACross-GBPUSD.
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderSubmitted(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-21, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderAccepted(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-21, order_id=B-GBP/USD-21, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] OrderFilled(account_id=SIM-000-SIMULATED, cl_ord_id=O-20080101-045159-000-GBPUSD-21, order_id=B-GBP/USD-21, position_id=B-GBP/USD-11, strategy_id=EMACross-GBPUSD, symbol=GBP/USD.SIM, side=SELL-TAKER, filled_qty=100,000, leaves_qty=0, avg_price=1.98495, commission=10.00 GBP, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2008-01-01T04:51:59.900Z [INF] Portfolio: GBP/USD.SIM net position = -100000
2008-01-01T04:51:59.900Z [INF] Portfolio: Updated SIM position maintenance margin to 0.00 USD
2008-01-01T04:51:59.900Z [INF] EMACross-GBPUSD: <--[EVT] PositionOpened(account_id=SIM-000-SIMULATED, position_id=B-GBP/USD-11, strategy_id=EMACross-GBPUSD, entry=SELL, avg_open=1.98495, SHORT 100,000 GBP/USD.SIM, id=bf8f8b2a-157a-0aff-8476-98e84a95cb28).
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98505,1.98510,0,0,2008-01-01T04:51:59.900Z"
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:51:59.900000+00:00"
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98480,1.98485,0,0,2008-01-01T04:51:59.900Z"
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Advanced clock to tick.timestamp "2008-01-01 04:51:59.900000+00:00"
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Generating tick...
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:51:59.900000+00:00 Received tick ---> "GBP/USD.SIM,1.98490,1.98495,253,253,2008-01-01T04:52:00.000Z"
2020-10-24T08:21:59.564Z [WRN] BacktestEngine: 2008-01-01 04:52:00+00:00 Advanced clock to tick.timestamp "2008-01-01 04:52:00+00:00"
```

Note how a tick with timestamp 04:51.59.900 prints which then triggers a bar with timestamp 04:51:00.000 (i.e. clock is moved backwards, which probably should not be allowed).

These ticks were removed by TickDataWrangler because bid_volume+ask_volume==0 but they were not
removed from bar data in data_client since volume is sum of 3 bars and != 0. It seems that adding a check to make sure all events occur in sequential order (i.e. the timestamp of a new event must be >= the current timestamp) would at least catch this issue and throw an error.

Apologize for not providing code to reproduce but I can put something together if this doesn't immediately explain the issue.

**Comment by cjdsellers** [comment] 2020-11-09 01:43
This is interesting.

I've added a condition to the `TestClock.advance_time` method to ensure the clock can't be wound backwards.
```
Condition.true(to_time >= self._time, "to_time >= self._time")  # Ensure monotonic
```

I've improved the docs to clarify its a monotonic clock. 

There was also a logical flaw in the sorting of time events in the engine. So its now sorting once all events up to a ticks timestamp have been collected into the list.

I've run the backtest engine through the full USDJPY and GBPUSD sets with various bar specs and that condition never tripped. It's potentially a logging issue, or an incorrect timestamp being assigned to the bar. Looking at the data the prices and volume look correct.

The `TickDataWrangler` could probably do with some refactoring in general, with some additional test coverage.

I'll keep looking into this. In the meantime I've pushed something onto develop.

Feel free to raise the other issues when you like.

**Comment by cjdsellers** [comment] 2020-11-12 23:42
I'll be looking into this more closely in the next few days.

I'm curious though, where did you place the logging for `Received tick --->` ?
It would be good to know when the strategy received the tick also. I'll recreate the above to check.

A question for you, what are your thoughts on the current handling of ticks and bars? The intent was to create as accurate a simulation as possible from the given data, in this case 1 minute bars. So the generation of ticks is artificial to get the machinery working as it would live. I believe it's always going to hit the high of the bar before it hits the low though... I had considered making this random too with an optional seed.

I'm not sure zero size ticks is the best solution for keeping the bar volumes consistent with the input data...

**Comment by tmorgan4** [comment] 2020-11-13 08:16
Appreciate your work on this. I've done a poor job of documenting these issues however I'll make an effort to do better as I come across others in the future. The whole version control thing is still a big foreign to me since I rarely collaborate
on projects in my line of work.

> I'm curious though, where did you place the logging for `Received tick --->` ?
> It would be good to know when the strategy received the tick also. I'll recreate the above to check.

I can't find my commit containing this logging statement but I'm nearly positive the `'Generating tick...'` & `'Received tick --->'` wrapped this line:
https://github.com/nautechsystems/nautilus_trader/blob/b445b7d2eb9fd273ed9d31a6781791ab3291c15b/nautilus_trader/backtest/engine.pyx#L363

The very next line is where the time is advanced (also shown in the log immediately after tick is received).
https://github.com/nautechsystems/nautilus_trader/blob/b445b7d2eb9fd273ed9d31a6781791ab3291c15b/nautilus_trader/backtest/engine.pyx#L364

> 
> A question for you, what are your thoughts on the current handling of ticks and bars? The intent was to create as accurate a simulation as possible from the given data, in this case 1 minute bars. So the generation of ticks is artificial to get the machinery working as it would live. I believe it's always going to hit the high of the bar before it hits the low though... I had considered making this random too with an optional seed.
> 
> I'm not sure zero size ticks is the best solution for keeping the bar volumes consistent with the input data...

I've been having this exact debate myself. The way OHLC prices are converted to ticks is clever. It's helpful for each (O, H, L, C) price to be treated as an independent tick to accurately fill stop and limit orders. The way the high price is always checked before the low was another issue I wanted to bring up so glad to see you're already aware. One possibility is to implement some type of random/probabilistic model similar to the fill model when both the high and low ticks trigger competing orders in a single timestamp (i.e. there's not enough info to reconstruct which one was hit first).

Another issue is that O, H, L prices (which are then converted to independent ticks) all share the same timestamp yet each is processed as if they are in sequential order and each is allowed to execute its own orders. I've come across several instances where the net_position is flipped multiple times during the same timestamp which probably shouldn't be allowed. An example of this occurs in a minimally modified `examples/strategies/ema_cross_simple.py`:

[OHL_multiple_orders_same_timestamp.txt](https://github.com/nautechsystems/nautilus_trader/files/5535507/OHL_multiple_orders_same_timestamp.txt)

I'll keep thinking about this and let you know if I come up with any other ideas. Interested to hear any other ideas you have.

**Comment by cjdsellers** [comment] 2020-11-14 01:47
I think the high always being generated before the low can be improved, its extremely unrealistic and could lead to erroneous conclusions about a strategies performance also. **Does anyone know of how other platforms handle bars in this way?**

The most accurate backtest would use the highest execution resolution possible with ticks. However that data may not be available to a user, or the computational cost for that level of accuracy simply isn't needed (e.g. such a trading hourly or daily bars).

The solution for ticks generated from bar data using something similar to the `FillModel` is the best one I can think of at the moment. My current thinking is the default behavior should be deterministic using a random seed (with the option to remove this if a user wants to do some kind of Monte Carlo).

The timestamps should be in order of generation in this case, rather than all occurring at the same time.

As for the multiple flipping this would fix the issue? If orders or so tight with that market that they're being triggered on each "tick" then this is also what would occur in the real world (provided latency is low enough to place the orders).

Thoughts?

**Comment by cjdsellers** [comment] 2020-11-17 02:59
So I've been working on a solution. There is now an optional `random_seed` param for the `pre_process` method. When one is passed then the high and low prices will be randomly swapped with probability 0.5.

```
        # Randomly shift high low prices
        if random_seed is not None:
            random.seed(random_seed)
            for i in range(0, len(df_ticks_o)):
                if random.getrandbits(1):
                    high = df_ticks_h.iloc[i]
                    low = df_ticks_l.iloc[i]
                    df_ticks_final.iloc[i + 1] = low
                    df_ticks_final.iloc[i + 2] = high
```

It's a work in progress though because the performance is quite slow. It takes several seconds to sort a month of data, and that's going to blow out for larger sets across multiple instruments.

I tried a few different approaches, a `DateTimeIndex` is immutable so once set you can't shift individual rows.

I also thought the `.sample()` method available on a `DataFrame` could be useful, however it will randomly take from anywhere so that's not going to work.

Another approach could be to randomly perturb the index for the highs and lows within a certain range before merging all of the dataframes together. Unfortunately this is likely to be slow too, the problem is the for loop rather than mapping a function or just broadcasting values.

I'm open to any suggestions.

**Comment by tmorgan4** [comment] 2020-11-17 07:46
Thanks for working to improve this! I want to look into a few of your ideas and see if I can find a way to speed things up.

**Comment by cjdsellers** [comment] 2020-11-17 10:57
Another idea is using a list or even memory view of the bid and ask prices, this would potentially allow faster indexing especially if you could broadcast a random perturbation function across each array at once (H/L bid and ask need to be moved at the same time). Then the data can be put into the `pd.DataFrame`.

**Comment by cjdsellers** [comment] 2021-01-07 20:41
@tmorgan4 Are you happy for me to make that change to the sorting, or did you want to do another PR?

**Comment by tmorgan4** [comment] 2021-01-08 08:50
@cjdsellers Please go ahead and make whatever changes you want to implement. Sorry for the lack of followup...haven't had much time to mess with this recently!

**Comment by cjdsellers** [comment] 2021-01-08 23:49
The above relates to discussion about PR #129. This has now been included in a commit from myself, with credits to @tmorgan4.

This current issue regarding the ordering of high and low ticks generated from historical bar data still stands.

**Comment by cjdsellers** [comment] 2021-07-09 05:57
I've put some thought into this and determined that this is most easily handled with a data pre-processing step - prior to being loaded as `QuoteTick`s or `TradeTick`s into a `BacktestEngine`.

If a strategy is sensitive to the ordering of the ticks derived from a bars high and low, then it is suggested that some custom wrangling builds rows of tick data (`pd.DataFrame` etc) with the ordering of the high and low randomized.

If anyone has come up with a similar solution which they'd like to contribute into the open source project then I'm very receptive to this!

Otherwise closing this issue for now.

**Closed by cjdsellers** 2021-07-09 05:57 UTC
Labels: enhancement
