### ISSUE TITLE
Events latency

### ISSUE THREAD

**Issue by cuberone** [nautechsystems/nautilus_trader#1963] opened 2024-09-27 12:07 UTC
# Bug Report
In the backtest, it seems some events that are supposed to be processed in the current time step are processed in the next time step. I configured the engine with `latency_model=None`. It occurs in a random manner.
Here I make two orders at the same time. The second order is accepted 1 minute later using 1-minute input data (see last row):
```
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderInitialized(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-7, side=BUY, type=LIMIT, quantity=0.032, time_in_force=GTC, post_only=False, reduce_only=False, quote_quantity=False, options={'price': '43537.30', 'display_qty': None, 'expire_time_ns': 0}, emulation_trigger=NO_TRIGGER, trigger_instrument_id=None, contingency_type=NO_CONTINGENCY, order_list_id=None, linked_order_ids=None, parent_order_id=None, exec_algorithm_id=None, exec_algorithm_params=None, exec_spawn_id=None, tags=['2'])
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: [CMD]--> SubmitOrder(order=LimitOrder(BUY 0.032 BTCUSDT-PERP.BINANCE LIMIT @ 43_537.30 GTC, status=INITIALIZED, client_order_id=O-20240106-095159-0-05-7, venue_order_id=None, position_id=None, tags=['2']), position_id=P-1704531419999000000-BACKTESTER-0-05)
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderSubmitted(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-7, account_id=BINANCE-001, ts_event=1704534719999000000)
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderInitialized(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-8, side=SELL, type=LIMIT, quantity=0.032, time_in_force=GTC, post_only=False, reduce_only=False, quote_quantity=False, options={'price': '43770.70', 'display_qty': None, 'expire_time_ns': 0}, emulation_trigger=NO_TRIGGER, trigger_instrument_id=None, contingency_type=NO_CONTINGENCY, order_list_id=None, linked_order_ids=None, parent_order_id=None, exec_algorithm_id=None, exec_algorithm_params=None, exec_spawn_id=None, tags=['0'])
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: [CMD]--> SubmitOrder(order=LimitOrder(SELL 0.032 BTCUSDT-PERP.BINANCE LIMIT @ 43_770.70 GTC, status=INITIALIZED, client_order_id=O-20240106-095159-0-05-8, venue_order_id=None, position_id=None, tags=['0']), position_id=P-1704531419999000000-BACKTESTER-0-05)
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderSubmitted(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-8, account_id=BINANCE-001, ts_event=1704534719999000000)
2024-01-06T09:51:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderAccepted(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-7, venue_order_id=BINANCE-1-043, account_id=BINANCE-001, ts_event=1704534719999000000)
2024-01-06T09:52:59.999000000Z [INFO] BACKTESTER-0.G: <--[EVT] OrderAccepted(instrument_id=BTCUSDT-PERP.BINANCE, client_order_id=O-20240106-095159-0-05-8, venue_order_id=BINANCE-1-044, account_id=BINANCE-001, ts_event=1704534719999000000)
```

### Specifications

- OS platform: macOS
- Python version: 3.11
- `nautilus_trader` version:  1.201.0

**Comment by ShengeZheng** [comment] 2024-10-01 04:14
I meet this too

**Comment by cjdsellers** [comment] 2024-10-07 20:42
Hi @cuberone and @ShengeZheng

Thanks for the report.

I've added a basic test to assert that multiple limit orders can be submitted and accept on the same timestamp:
https://github.com/nautechsystems/nautilus_trader/blob/develop/tests/unit_tests/backtest/test_exchange_margin.py#L352

So there must be something else more subtle going on here. If you could provide a minimum reproducible example highlighting the behavior, then it would help me to identify and fix.

**Comment by cuberone** [comment] 2024-10-10 11:23
Since all the events in the sample have the correct ts_event value, I believe the discrepancy is due to logger latency, not event handling latency. I propose closing the issue.

**Comment by cjdsellers** [comment] 2024-10-10 18:32
I think for backtesting using a static test clock, we'd expect those events to be logged on the same timestamp though. I think there is still something subtle happening in this scenario.

It would help with debugging if you share more of the logs, or a code snippet of how you're submitting the orders. An MRE would be even better, but I understand they take time to set up.

**Comment by cjdsellers** [comment] 2024-10-12 21:25
I'll close this for now, because I have no further leads to be able to debug.

We can open this ticket again and continue if either of you are able to provide more context on the scenario, logs, or a failing MRE. Thanks once again :pray:.

**Closed by cjdsellers** 2024-10-12 21:25 UTC
Labels: bug
