### ISSUE TITLE
Issue importing `nautilus_trader.model.data.bar` on M1 mac

### ISSUE THREAD

**Issue by this-josh** [nautechsystems/nautilus_trader#1158] opened 2023-06-28 17:32 UTC
# Bug Report

I'm new to nautilus and wanted to have a go at the quickstart but I've encountered an issue while installing. I'm following [the docs](https://docs.nautilustrader.io/getting_started/installation.html)

I am able to run `https://raw.githubusercontent.com/nautechsystems/nautilus_data/main/scripts/hist_data_to_catalog.py` so it would seem the issue is specific to the `bar` module. 

### Expected Behavior
Import to work

### Actual Behavior
```python
>>> from nautilus_trader.persistence.catalog import ParquetDataCatalog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/nautilus_trader/persistence/catalog/__init__.py", line 16, in <module>
    from nautilus_trader.persistence.catalog.base import BaseDataCatalog
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/nautilus_trader/persistence/catalog/base.py", line 21, in <module>
    from nautilus_trader.model.data import Bar
  File "/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/nautilus_trader/model/data/__init__.py", line 18, in <module>
    from nautilus_trader.model.data.bar import Bar
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/del/lib/python3.11/site-packages/nautilus_trader/model/data/bar.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

### Steps to Reproduce the Problem

1. Create a clean conda env `conda create -n del python=3.11 -y `
2. `pip install -U nautilus_trader`
3. `from nautilus_trader.persistence.catalog import ParquetDataCatalog`

### Specifications

- OS platform: MacOS 13.4
- Python version: 3.11
- `nautilus_trader` version: `nautilus_trader-1.175.0-cp311-cp311-macosx_13_0_arm64.whl`

**Comment by this-josh** [comment] 2023-06-29 06:31
Yes, the last line of the error confirms it is using the `del` environment: `/opt/homebrew/Caskroom/miniforge/base/envs/del` 

I tried installing from source following [this](https://docs.nautilustrader.io/getting_started/installation.html#from-source), and I got the same error:
```python
>>> from nautilus_trader.persistence.catalog import ParquetDataCatalog
...
ImportError: dlopen(.../nautilus_trader/nautilus_trader/model/data/bar.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

**Comment by davidsblom** [comment] 2023-06-29 12:55
I'm having this problem as well. I've built from source on a MacBook Air with an M2 CPU.

```
(market-master) davidblom@Davids-MacBook-Air market-master % poetry run python live/app.py
Traceback (most recent call last):
  File "/Users/davidblom/repositories/market-master/live/app.py", line 4, in <module>
    from nautilus_trader.adapters.binance.common.enums import BinanceAccountType
  File "/Users/davidblom/miniconda3/envs/market-master/lib/python3.10/site-packages/nautilus_trader/adapters/binance/common/enums.py", line 29, in <module>
    from nautilus_trader.model.data import BarSpecification
  File "/Users/davidblom/miniconda3/envs/market-master/lib/python3.10/site-packages/nautilus_trader/model/data/__init__.py", line 19, in <module>
    from nautilus_trader.model.data.bar import Bar
ImportError: dlopen(/Users/davidblom/miniconda3/envs/market-master/lib/python3.10/site-packages/nautilus_trader/model/data/bar.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

When starting python interactively and loading the `nautilus_trader` module, it only fails on the `nautilus_trader.model.data` module:

```
(market-master) davidblom@Davids-MacBook-Air market-master % poetry run python
Python 3.10.11 (main, May 17 2023, 14:30:36) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nautilus_trader
>>> import nautilus_trader.model
>>> import nautilus_trader.model.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidblom/miniconda3/envs/market-master/lib/python3.10/site-packages/nautilus_trader/model/data/__init__.py", line 19, in <module>
    from nautilus_trader.model.data.bar import Bar
ImportError: dlopen(/Users/davidblom/miniconda3/envs/market-master/lib/python3.10/site-packages/nautilus_trader/model/data/bar.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

Interestingly, when using `ipython`, the module is successfully imported :-)

```
(market-master) davidblom@Davids-MacBook-Air market-master % poetry run ipython
Python 3.10.11 (main, May 17 2023, 14:30:36) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import nautilus_trader

In [2]: import nautilus_trader.model

In [3]: import nautilus_trader.model.data

In [4]: import nautilus_trader.model.data.bar

In [5]: from nautilus_trader.model.data.bar import Bar

In [6]: exit()
```

**Comment by cjdsellers** [comment] 2023-06-30 07:43
So for this one I think the issue is that you need a Python install which allows shared objects, as per [the docs](https://github.com/nautechsystems/nautilus_trader#from-source) there's a way to achieved this when installing Python.

Unfortunately it seems Conda environments don't have this enabled by default, and therefore don't seem to play too nicely with C extensions involving static linking of FFI code, and use of shared objects.

I've seen repeated issues using Conda with this codebase (and others involving C extensions), my best advice is to just use pyenv with the vanilla Python installs it will give you (with shared objects enabled as per the above). The next time I do a pass over the docs I'll be sure to add some commentary around this.

You may also find there is an equivalent flag/option when installing a new Conda environment.

I'm going to close this for now as I don't consider it a fundamental bug with the codebase or build, but the configuration of the Python environment Nautilus is being installed into, and an unfortunate consequence of the complexity of a hybrid codebase involving interoping of three different languages.

Please let me know if you think I've misunderstood the issue, or if you want to share any further insights around this! :pray:

**Closed by cjdsellers** 2023-06-30 07:43 UTC
Labels: bug

**Comment by cjdsellers** [comment] 2023-06-30 07:45
Just for added colour too, I also own a MacBook M1, and installation as per the docs does work for that platform.

**Comment by this-josh** [comment] 2023-06-30 07:49
Thank you for your explanation this makes sense. I've been meaning to transition from conda for a while now, I had a feeling it was causing this issue too. But I presumed it was to do with new envs not being clean.

I think it's okay not to support conda, but given the issue has arisen a few times it might be worth specifying this in the readme to prevent duplicate issues. 

Ah great. Given this, I'll remove conda and try again. Cheers.

**Comment by cjdsellers** [comment] 2023-06-30 07:51
Thanks @this-josh 

I'll make sure to update the README installation notes over the weekend, calling out the potential issue with Conda environments.

**Comment by this-josh** [comment] 2023-06-30 09:18
I have abandoned conda and successfully installed nautilus from my pyenv python. The Readme should maybe be also updated to reflect [pyenv having `--enable-shared` as the default now](https://github.com/pyenv/pyenv/issues/2294) as specifying it manually produced an error for me.

**Comment by cjdsellers** [comment] 2023-06-30 09:22
> I have abandoned conda and successfully installed nautilus from my pyenv python. The Readme should maybe be also updated to reflect [pyenv having `--enable-shared` as the default now](https://github.com/pyenv/pyenv/issues/2294) as specifying it manually produced an error for me.

Great, thanks for sharing that! good to know.

**Comment by rterbush** [comment] 2023-06-30 13:24
fwiw, I've been using conda from day one with Nautilus and haven't done anything special that I am aware of. When the Apple Silicon Macs came out, conda was the only way to get a fully working python env for things like tensorflow. I assume that has changed by now and probably should migrate to pyenv...

**Comment by this-josh** [comment] 2023-07-03 19:19
Three days later I've found myself needing a package only available on Conda-forge... 

You're right though, building from source escapes this issue.
