### ISSUE TITLE
Backtesting process halts upon Unsubscribing from Internal TimeBars during Mid-Test

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1606] opened 2024-04-23 13:20 UTC
# Bug Report

Backtesting process halts upon unsubscribing from Internal TimeBars during a test.

### Expected Behavior
Backtest shouldn't raise exception.

### Actual Behavior
Raises exception and stops abnormally.

### Steps to Reproduce the Problem

1. Run backtest multiple strategies having Internal time-based Bar subscription
2. Stop and Unsubscribe the Bars for any of the Strategy (real use case as the FuturesContract approaching expiry)
3. Backtest terminates with below exception

```
  File "nautilus_trader\\backtest\\engine.pyx", line 928, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader\\backtest\\engine.pyx", line 1090, in nautilus_trader.backtest.engine.BacktestEngine._run
  File "nautilus_trader\\backtest\\engine.pyx", line 1179, in nautilus_trader.backtest.engine.BacktestEngine._advance_time
  File "nautilus_trader\\backtest\\engine.pyx", line 1226, in nautilus_trader.backtest.engine.BacktestEngine._process_raw_time_event_handlers
  File "nautilus_trader\\data\\aggregation.pyx", line 730, in nautilus_trader.data.aggregation.TimeBarAggregator._build_bar
  File "nautilus_trader\\data\\aggregation.pyx", line 753, in nautilus_trader.data.aggregation.TimeBarAggregator._build_bar
  File "nautilus_trader\\common\\component.pyx", line 619, in nautilus_trader.common.component.TestClock.next_time_ns
  File "nautilus_trader\\core\\correctness.pyx", line 790, in nautilus_trader.core.correctness.Condition.valid_string
  File "nautilus_trader\\core\\correctness.pyx", line 145, in nautilus_trader.core.correctness.Condition.not_none
TypeError: The 'name' argument was None
```

### Specifications

- OS platform: Win 11
- Python version: 3.11.6
- `nautilus_trader` version: 1.192.0 (develop)

**Comment by benjaminsingleton** [comment] 2024-04-23 17:33
I'm also getting the same portfolio not initialized failure in live (paper) trading. Not sure if that's definitely related to this issue. I can post the full logs later today.

**Comment by cjdsellers** [comment] 2024-04-23 21:42
This just seems to affect internally aggregated time bars.

When there are no more subscribers, the `DataEngine` stops the aggregator which cancels its internal timer - then for some reason the [timer name is set to `None`](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/data/aggregation.pyx#L660).

I feel like removing this is a bit of a Chesterton fence thing, but I "can't see a good reason for having this here" and all the tests seem to pass after I remove it.

Pushed to `develop` branch.

The other issue regarding `name` is unrelated to this, and was probably caused by a change to accommodate multiple clients where the `name` wasn't actually being wired through to the `client_id`. I haven't dug into it yet though.

Closing this one as fixed, and lets open a specific issue for the `Portfolio` problem, logs or a stack trace would be helpful :pray:.

**Closed by cjdsellers** 2024-04-23 21:42 UTC
Labels: bug

**Comment by rsmb7z** [comment] 2024-04-23 22:09
> Pushed to `develop` branch.

Works like a charm—thanks for the fix!
