### ISSUE TITLE
Account balances are not calculated properly for CASH accounts

### ISSUE THREAD

**Issue by imcu** [nautechsystems/nautilus_trader#436] opened 2021-09-10 14:46 UTC
We have the following scenario:

Account type: CASH
Balances 1_000_000 USDT / 10 BTC account_type = CASH

Actions: 
1) short 5 BTC with limit order
2) buy back 5 BTC with limit order

Resulting account balances:
```
2021-09-10T06:42:41.121982Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2021-09-10T06:42:41.121995Z [INF] BACKTESTER-001.BacktestEngine:  SIM-001
2021-09-10T06:42:41.122002Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2021-09-10T06:42:41.122043Z [INF] BACKTESTER-001.BacktestEngine: Account balances (starting): 1_000_000.00000000 USDT, 10.00000000 BTC
2021-09-10T06:42:41.122053Z [INF] BACKTESTER-001.BacktestEngine: Account balances (ending):   1_001_858.76443950 USDT, 14.81443950 BTC
2021-09-10T06:42:41.122061Z [INF] BACKTESTER-001.BacktestEngine: Commissions (total):                                 -4.81443950 USDT
2021-09-10T06:42:41.122068Z [INF] BACKTESTER-001.BacktestEngine: Unrealized PnLs:                                                     
2021-09-10T06:42:41.122075Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
```

Account type: MARGIN
Balances 1_000_000 USDT / 10 BTC account_type = CASH

Actions: 
1) short 5 BTC with limit order
2) buy back 5 BTC with limit order

Resulting account balances:
```
2021-09-10T06:44:51.167066Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2021-09-10T06:44:51.167075Z [INF] BACKTESTER-001.BacktestEngine:  SIM-001
2021-09-10T06:44:51.167082Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2021-09-10T06:44:51.167129Z [INF] BACKTESTER-001.BacktestEngine: Account balances (starting): 1_000_000.00000000 USDT, 10.00000000 BTC
2021-09-10T06:44:51.167141Z [INF] BACKTESTER-001.BacktestEngine: Account balances (ending):   1_001_858.76443950 USDT, 10.00000000 BTC
2021-09-10T06:44:51.167148Z [INF] BACKTESTER-001.BacktestEngine: Commissions (total):                                 -4.81443950 USDT
2021-09-10T06:44:51.167155Z [INF] BACKTESTER-001.BacktestEngine: Unrealized PnLs:                                                     
2021-09-10T06:44:51.167163Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
```

**Comment by cjdsellers** [comment] 2021-09-12 12:57
This was being caused by a conditional which was incorrectly assuming commissions are non-negative (negative commissions represent a rebate).

Now fixed from 77fcd97.

**Closed by cjdsellers** 2021-09-12 12:57 UTC
Labels: bug
