### ISSUE TITLE
Add maker_fee and taker_fee params to FuturesContract and OptionsContract __init__()

### ISSUE THREAD

**Issue by naught2020** [nautechsystems/nautilus_trader#1717] opened 2024-06-17 06:15 UTC
# Bug Report
maker_fee and taker_fee arguments are missing in instruments __init__ method, FuturesContract and OptionContract fee is always default value Decimal(0).

**Comment by cjdsellers** [comment] 2024-06-20 06:50
Thanks for the report @naught2020

One reason this is missing is because we have plans for moving fee and margin related fields off instruments and into `FeeModel` and the venue config. 

We're currently still deciding if it makes sense to add these params for consistency and accept the overhead of wiring this all throughout the platform into Rust and back to the SQL schemas - or, proceed with the above refactoring instead.

I'll change this ticket over to an enhancement request as this is a known limitation and not a bug as such.

**Comment by stentor2018** [comment] 2024-08-16 00:27
hi! i would like to know if  there is any progress about this enhancement?

**Comment by cjdsellers** [comment] 2024-08-17 23:17
Hi @stentor2018 

This is actually blocked right now pending a refactoring of fee modeling.

We didn't want to spend time adding these parameters everywhere (which takes significant time including through Rust), when we're moving to decoupling this from the instrument definitions.

Thanks for your patience 🙏.

**Comment by naught2020** [comment] 2024-08-18 04:01
got it, thanks for your reply! I will keep waiting.

**Comment by stefansimik** [comment] 2024-12-15 22:55
Isn't this already solved in latest release 1.208.0 Beta?

![Image](https://github.com/user-attachments/assets/4ddd9404-e670-421e-9c7e-30ad2fef5f53)

**Comment by cjdsellers** [comment] 2024-12-15 22:58
Thanks @stefansimik

This one can be closed as completed.

**Closed by cjdsellers** 2024-12-15 22:58 UTC
Labels: enhancement
