### ISSUE TITLE
Suggestion: Upload nightly wheels to `Releases` instead of a repository branch

### ISSUE THREAD

**Issue by sunlei** [nautechsystems/nautilus_trader#2099] opened 2024-12-12 06:32 UTC
# Suggestion

Hi,
I noticed that the nightly build artifacts are currently being pushed to a specific branch in the repository and published via GitHub Pages. While this approach works, it may lead to a rapid increase in the repository size over time.

Would it be possible to upload the nightly wheels directly to the `Releases` section instead? This would help keep the repository lean.

- [gh release upload](https://cli.github.com/manual/gh_release_upload)

Thanks for considering this suggestion!

**Comment by cjdsellers** [comment] 2024-12-12 07:33
Hi @sunlei

Thanks for your suggestion.

The intent of setting up the `packages` branch with GitHub Pages was to avoid cluttering both PyPI and GitHub releases with daily nightly builds. It was initially meant to be set up as an orphan branch (like the old `gh-pages` branch) that wouldn't contribute to the overall repo size unless specifically checked out.

However, after checking the git history, I can see it wasn't created as a proper orphan branch. This means it's currently sharing history with the main repository, which isn't ideal and will lead to bloating as you suggest.

I'll fix this up soon and will also look at pruning some other stale branches as well.

**Comment by cjdsellers** [comment] 2024-12-12 10:14
Hi @sunlei

Thanks again for raising this. I've now fixed the issue - I just recreated the packages branch as a proper orphan branch. Verified this by doing a fresh clone of just the `packages` branch which shows only a single commit with no connection to the main repository history:

```
* b8ab0f5 (HEAD -> packages, origin/packages) Initial commit
```

This means the branch is now properly isolated and won't contribute to the repository's overall size unless specifically checked out. The wheels remain accessible via GitHub Pages as before, but now in a more optimized way.

Thanks again!

**Closed by cjdsellers** 2024-12-12 10:14 UTC
Labels: improvement

**Comment by sunlei** [comment] 2024-12-12 10:38
@cjdsellers 

But GitHub Pages has [some limits](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#limits-on-use-of-github-pages):
- Published GitHub Pages sites may be no larger than 1 GB
- GitHub Pages sites have a soft bandwidth limit of 100 GB per month

**Comment by cjdsellers** [comment] 2024-12-12 11:05
In this case, we could maintain the latest nightly wheel to `Releases` - but it wouldn't be a clean solution to maintain the last ~30 nightly builds under pre-releases.

Also, I'm not sure pip would work in this case either - so potentially the best solution is external package hosting after all.

I see tensorflow for example just uploads nightly wheels to PyPI and doesn't maintain GitHub releases for those. This might work if its possible to delete releases from PyPI in an automated way (I'd suspect this is possible), with a separate nightly project to get another 10 GB of storage allocation.

Otherwise there are a few other options. Pages would have worked if not for these limits, but it _is_ stretching the use case for which pages was intended.

**Comment by sunlei** [comment] 2024-12-12 17:33
@cjdsellers

It is suggested to create a `nautechsystems/nautilus_trader_nightly_release` repository and upload the build artifacts to the `releases` of this repository.

Then, put links in the simple index at https://nautechsystems.github.io

Do you think this approach is worth trying? It might address the issues we discussed earlier.

**Comment by cjdsellers** [comment] 2024-12-13 07:19
Hi @sunlei 

We need to retain `pip install` capabilities, and a standard repository isn’t suitable for static file hosting since it doesn’t serve files the same way as GH pages (pypi-style package hosting won’t work like that).

I think the best approach here is to just go with external package hosting (which I'm investigating), and in the mean time we can maintain a 2-3 day lookback for the nightly wheel builds to stay under the 1 GB limit.

**Comment by sunlei** [comment] 2024-12-13 07:24
@cjdsellers 

The files uploaded to the Releases section will have links like `https://github.com/nautechsystems/nautilus_trader/releases/download/v1.207.0/nautilus_trader-1.207.0-cp312-cp312-manylinux_2_35_x86_64.whl`.

Would it be feasible to use `GitHub Pages` to publish a simple index page compatible with `pip install`, like existing `https://nautechsystems.github.io/nautilus_trader/simple/`

And then use the download links from the `Releases` section on that page?

**Comment by cjdsellers** [comment] 2024-12-13 08:29
It's a creative approach, but I think there might be several issues with it.

- We don't actually want to bloat the release history with nightly wheels (tensorflow is a good reference for this, only RC's or stable versions are releases).
- The `index.html` lists wheel files for the directory, and there is a particular structure pip expects, so I don't think we could use urls in place of the file names.

There are some reasonable external
hosting solutions which I still think would be the cleanest approach overall?
