### ISSUE TITLE
Binance: reconciling the execution state fails due to a TypeError(an integer is required)

### ISSUE THREAD

**Issue by davidblom603** [nautechsystems/nautilus_trader#1154] opened 2023-06-27 11:25 UTC
# Bug Report

### Expected Behavior
The execution state is successfully reconciled without any errors.

### Actual Behavior
During initialization, the Binance execution client fails and the script is crashed. There is a TypeError exception thrown with the message that an integer is required.
```
2023-06-27T11:21:09.338621500Z [INF] TESTER-001.ExecClient-BINANCE: Nautilus clock time 1687864869338 UNIX (ms).
2023-06-27T11:21:09.338636917Z [INF] TESTER-001.ExecClient-BINANCE: Listen key 78FpuD6MkI2HcH7W8rIG73vzVTDg8xAHUAWwSM1GUpltwUMCaAlWUoKVTvw3
2023-06-27T11:21:09.338660958Z [DBG] TESTER-001.ExecClient-BINANCE: Creating task _ping_listen_keys.
2023-06-27T11:21:09.338858792Z [INF] TESTER-001.BinanceWebSocketClient: Connecting to wss://testnet.binance.vision/stream?streams=78FpuD6MkI2HcH7W8rIG73vzVTDg8xAHUAWwSM1GUpltwUMCaAlWUoKVTvw3
2023-06-27T11:21:09.339619583Z [DBG] TESTER-001.ExecClient-BINANCE: Scheduled `ping_listen_keys` to run in 300s.
2023-06-27T11:21:10.806248459Z [DBG] TESTER-001.ExecEngine: Checking in-flight orders status...
2023-06-27T11:21:10.806354584Z [DBG] TESTER-001.ExecEngine: Found 0 orders in-flight.
2023-06-27T11:21:11.094676168Z [INF] TESTER-001.BinanceWebSocketClient: Connected.
2023-06-27T11:21:11.095416626Z [INF] TESTER-001.ExecClient-BINANCE: Connected
2023-06-27T11:21:11.095809043Z [INF] TESTER-001.TradingNode: Awaiting execution state reconciliation (10.0s timeout)...
2023-06-27T11:21:11.097265668Z [INF] TESTER-001.ExecClient-BINANCE: Generating ExecutionMassStatus for BINANCE...
2023-06-27T11:21:11.099038084Z [INF] TESTER-001.ExecClient-BINANCE: Generating OrderStatusReports for BINANCE...
2023-06-27T11:21:11.100834626Z [INF] TESTER-001.ExecClient-BINANCE: Generating TradeReports for BINANCE...
2023-06-27T11:21:11.100984418Z [INF] TESTER-001.ExecClient-BINANCE: Generated 0 TradeReports.
2023-06-27T11:21:11.101019418Z [INF] TESTER-001.ExecClient-BINANCE: Generating PositionStatusReports for BINANCE...
2023-06-27T11:21:11.101036751Z [INF] TESTER-001.ExecClient-BINANCE: Generated 0 PositionStatusReports.
2023-06-27T11:21:11.441196709Z [INF] TESTER-001.DataClient-BINANCE: Awaiting subscriptions...
2023-06-27T11:21:11.441292959Z [DBG] TESTER-001.DataClient-BINANCE: Scheduled `connect_websockets` to run in 4s.
2023-06-27T11:21:12.806634002Z [ERR] TESTER-001.ExecClient-BINANCE: Cannot reconcile execution state
TypeError(an integer is required)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/live/execution_client.py", line 427, in generate_mass_status
    reports = await asyncio.gather(
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/binance/common/execution.py", line 402, in generate_order_status_reports
    report = order.parse_to_order_status_report(
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/binance/common/schemas/account.py", line 213, in parse_to_order_status_report
    return OrderStatusReport(
  File "nautilus_trader/execution/reports.pyx", line 167, in nautilus_trader.execution.reports.OrderStatusReport.__init__
```

### Steps to Reproduce the Problem

1. Run the volality_market_master.py example and submit orders. 
2. Stop the execution of the trading strategy with CTRL-C.
3. Restart the python script

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by cjdsellers** [comment] 2023-06-28 09:44
Hi @davidblom603

Thanks so much for the report.

I traced this down to incorrect parsing of the trigger type for orders, the default value of `TriggerType.NO_TRIGGER` wasn't being correctly set (the `OrderStatusReport` expects an integer for this value as its going into C).

As a downstream consequence, the entire mass status report was failing, and a `None` value was turning up in `_reconcile_mass_status`. This is now validated and an error properly logged.

Pushed to `develop` branch just now.

I couldn't reproduce on my side, but please let me know if this fix works so I can close this issue.

**Comment by davidblom603** [comment] 2023-06-28 19:19
Hmm. Having some trouble installing the rust compilers due to some firewall restrictions.
Feel free to close the issue. Currently don't have a way to test the develop branch, so I'll let you know once I can grab another laptop.

**Comment by davidblom603** [comment] 2023-06-29 07:03
just tested the fix and it seems to work. Appreciate it!

**Comment by davidblom603** [comment] 2023-06-29 07:09
hmm tried another time and it is still complaining.
```
2023-06-29T07:08:05.030106419Z [INF] TESTER-001.ExecClient-BINANCE: Listen key YEqDogCfRJyuvcRdLxS6PSmJqKRgDSCM1lHTvne2UeAReBsrYoyJmmyKZ7Fp
2023-06-29T07:08:05.030126002Z [DBG] TESTER-001.ExecClient-BINANCE: Creating task _ping_listen_keys.
2023-06-29T07:08:05.030293460Z [INF] TESTER-001.BinanceWebSocketClient: Connecting to wss://testnet.binance.vision/stream?streams=YEqDogCfRJyuvcRdLxS6PSmJqKRgDSCM1lHTvne2UeAReBsrYoyJmmyKZ7Fp
2023-06-29T07:08:05.031002210Z [DBG] TESTER-001.ExecClient-BINANCE: Scheduled `ping_listen_keys` to run in 300s.
2023-06-29T07:08:06.337051544Z [INF] TESTER-001.BinanceWebSocketClient: Connected.
2023-06-29T07:08:06.337505669Z [INF] TESTER-001.ExecClient-BINANCE: Connected
2023-06-29T07:08:06.337831294Z [INF] TESTER-001.TradingNode: Awaiting execution state reconciliation (10.0s timeout)...
2023-06-29T07:08:06.339127461Z [INF] TESTER-001.ExecClient-BINANCE: Generating ExecutionMassStatus for BINANCE...
2023-06-29T07:08:06.340853419Z [INF] TESTER-001.ExecClient-BINANCE: Generating OrderStatusReports for BINANCE...
2023-06-29T07:08:06.342739461Z [INF] TESTER-001.ExecClient-BINANCE: Generating TradeReports for BINANCE...
2023-06-29T07:08:06.342878211Z [INF] TESTER-001.ExecClient-BINANCE: Generated 0 TradeReports.
2023-06-29T07:08:06.342915378Z [INF] TESTER-001.ExecClient-BINANCE: Generating PositionStatusReports for BINANCE...
2023-06-29T07:08:06.342931128Z [INF] TESTER-001.ExecClient-BINANCE: Generated 0 PositionStatusReports.
2023-06-29T07:08:06.551183170Z [DBG] TESTER-001.ExecEngine: Checking in-flight orders status...
2023-06-29T07:08:06.551233878Z [DBG] TESTER-001.ExecEngine: Found 0 orders in-flight.
2023-06-29T07:08:07.117182461Z [INF] TESTER-001.DataClient-BINANCE: Awaiting subscriptions...
2023-06-29T07:08:07.117258753Z [DBG] TESTER-001.DataClient-BINANCE: Scheduled `connect_websockets` to run in 4s.
2023-06-29T07:08:07.378922212Z [ERR] TESTER-001.ExecClient-BINANCE: Cannot reconcile execution state
ValueError(The 'trigger_type' <enum 'TriggerType'> of 0 was equal to the 'NONE' <enum 'TriggerType'> of 0)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/live/execution_client.py", line 427, in generate_mass_status
    reports = await asyncio.gather(
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/binance/common/execution.py", line 402, in generate_order_status_reports
    report = order.parse_to_order_status_report(
  File "/root/.cache/pypoetry/virtualenvs/market-master-vBA8rXtC-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/binance/common/schemas/account.py", line 213, in parse_to_order_status_report
    return OrderStatusReport(
  File "nautilus_trader/execution/reports.pyx", line 181, in nautilus_trader.execution.reports.OrderStatusReport.__init__
  File "nautilus_trader/core/correctness.pyx", line 346, in nautilus_trader.core.correctness.Condition.not_equal

2023-06-29T07:08:07.380818420Z [DBG] TESTER-001.ExecEngine: [RECV][RPT] None.
2023-06-29T07:08:17.436403425Z [WRN] TESTER-001.TradingNode: Timed out (10.0s) waiting for node to stop.
Status
------

```

**Comment by davidblom603** [comment] 2023-06-29 07:13
it seems to fail a test here: https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/execution/reports.pyx#L181C22-L181C22

**Comment by cjdsellers** [comment] 2023-06-29 09:41
Thanks for the heads up, I think the issue is that its a `Decimal(0)` which is not `None` and then evaluating that condition.

I've added a bit of logic which should fix it. Also, there isn't a strong reason to even have these reports in Cython, as they're not in any performance critical path and it would actually make these sorts of bugs less likely.

Will push the fix to `develop` shortly, just attending to the other Binance bug now.

**Comment by cjdsellers** [comment] 2023-06-30 07:35
Hi @davidblom603 

Did you get a chance to test again yet?

**Comment by davidblom603** [comment] 2023-06-30 07:55
Hi @cjdsellers ,
Thanks for the reminder. Tried to compile it on my laptop yesterday, but had some issues with getting it to run on a MacBook M2. I've shared my feedback on the other issue report. So, not done yet.

**Comment by davidblom603** [comment] 2023-06-30 08:00
just reading through your feedback there, I'll follow the docs to install it on Mac.

**Comment by davidsblom** [comment] 2023-06-30 19:25
@cjdsellers It works!

**Comment by cjdsellers** [comment] 2023-06-30 21:55
Excellent, I'll close this then.

**Closed by cjdsellers** 2023-06-30 21:55 UTC
Labels: bug
