### ISSUE TITLE
Websocket missed data

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#1184] opened 2023-07-22 15:19 UTC
# Bug Report
Flooding warnings which most likely means that we skipping data from binance websocket.

### Expected Behavior
Without skipping any data from websocket.

### Actual Behavior
Sometimes big number of such warning message appears:
`[WRN] TRADER-001.DataEngine: Blocking on '_data_queue.put' as queue full at 10000 items.`

It's happens only in 1.175, downgrading to 1.174 solved the issue.
* It can appear combined with another error (which appears when we additionally subscribe on trade ticks):
`[ERR] TRADER-001.DataClient-BINANCE: Error handling websocket message, Invalid enum value 'INSURANCE_FUND' - at '$.data.X'`,  
* sometimes after getting additional data by requests from binance in `on_start` method
* but there were cases without any visible triggers at all.

### Steps to Reproduce the Problem

1.Run 1.175 version and subscribe on quote ticks (with or without trade ticks)
2.In the some different moment got big number (on each quote tick?) warning message.

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.11
- `nautilus_trader` version: 1.175

**Comment by cjdsellers** [comment] 2023-07-24 11:40
Hi @Tzumx 

Thanks for the report here. I see several issues going on:
- Potential blocking of the event loop which is causing the queue in the `DataEngine` to become full?
- An undocumented enum value being sent by Binance `INSURANCE_FUND`

For the first one, so that I understand more about the context, what sort of data processing are you doing in body of `on_start` and approximately how long might his take?

Another user has reported to me this queue becoming full issue related to historical data requests, so there's potentially something going on here with the platform - and not just user strategy code blocking the event loop. We need to gather some more information though, are you able to provide any additional logs?

For the second point, that error is coming from the `msgspec` library, which has very strict parsing validations - it will raise a `ValueError` if an enum field parses to a value which is not a member of the enum. I did a search through the Binance API docs and couldn't see `INSURANCE_FUND` mentioned, although I think its a feature of the margin account. Also the `.X` field seems to be always related to Binance `OrderStatus`. Could you provide any more information on which message type was received over the websocket immediately prior to that error?

Looking forward to your response so we can dig in further and solve the issues!

**Comment by Tzumx** [comment] 2023-07-24 13:24
Thanks for your reply!! I'll try to provide all information I have despite there are not a lot of ((
1. `_data_queue.put` issue
   a. "on_start": in this case we're getting additional historical data from binance via a common sync request to their API and yes, it could take a few seconds there and block event loop for that time. Was unexpected because on 1.174 had the same requests code without any issues.
   b. but more strange for me that it can appear long after `on_start` and even if I remove the requests code from `on_start`, but unfortunately there weren't any useful messages:
```
[1m2023-07-21T01:20:49.472486299Z[0m [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...[0m
[1m2023-07-21T01:20:49.472515314Z[0m [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.[0m
[1m2023-07-21T01:20:51.472367737Z[0m [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...[0m
[1m2023-07-21T01:20:51.472396121Z[0m [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.[0m
[1m2023-07-21T01:20:55.843948973Z[0m [1;33m[WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.[0m
[1m2023-07-21T01:20:55.844041487Z[0m [1;33m[WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.[0m
```

2. `INSURANCE_FUND` issue:
Unfortunately even with DEBUG log level there weren't any useful logs again: only standard logs
```
[1m2023-07-24T09:47:25.905287508Z[0m [DBG] TRADER-001.ExecClient-BINANCE: Pinging WebSocket listen key ..........[0m
[1m2023-07-24T09:47:26.925346458Z[0m [DBG] TRADER-001.ExecClient-BINANCE: Scheduled `ping_listen_keys` to run in 300s.
[1m2023-07-24T09:47:28.589775925Z[0m [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...[0m
[1m2023-07-24T09:47:28.589808036Z[0m [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.[0m
......
[1m2023-07-24T09:50:00.596563463Z[0m [DBG] TRADER-001.ExecEngine: Checking in-flight orders status...[0m
[1m2023-07-24T09:50:00.596593249Z[0m [DBG] TRADER-001.ExecEngine: Found 0 orders in-flight.[0m
[1m2023-07-24T09:50:01.157502690Z[0m [1;31m[ERR] TRADER-001.DataClient-BINANCE: Error handling websocket message, Invalid enum value 'INSURANCE_FUND' - at `$.data.X`[0m
[1m2023-07-24T09:50:01.164681390Z[0m [1;31m[ERR] TRADER-001.DataClient-BINANCE: Error handling websocket message, Invalid enum value 'INSURANCE_FUND' - at `$.data.X`[0m
.....
```
All can I add there that looks like those error messages appears only if we subscribe for trade ticks.
Found only [that](https://www.binance.com/en/support/faq/introduction-to-insurance-funds-360033525371) mention in binance about this fund

**Comment by cjdsellers** [comment] 2023-07-27 08:07
To be able to better debug I'd need to be able to reproduce on my end, which instruments are you subscribing to trade ticks for?

**Comment by Tzumx** [comment] 2023-07-27 08:17
Sure. It wasn't a lot:
`"ADAUSDT-PERP.BINANCE","BCHUSDT-PERP.BINANCE","BNBUSDT-PERP.BINANCE","BTCUSDT-PERP.BINANCE", "DYDXUSDT-PERP.BINANCE","ETHUSDT-PERP.BINANCE","SOLUSDT-PERP.BINANCE","XRPUSDT-PERP.BINANCE"`

**Comment by cjdsellers** [comment] 2023-07-27 08:29
Thanks for providing that @Tzumx 

I just setup a test strategy to subscribe to quote and trade ticks for the above instruments and testing this on the latest release 1.175 and also `develop` branch 1.176 (soon to be released), left it running for a few minutes with each version.

I'm not able to reproduce, potentially some other data you're requested contains this `INSURANCE_FUND` value, or maybe a trade related to one of the above instruments?

**Comment by Tzumx** [comment] 2023-07-27 09:30
Thanks for your quick reply! 
1. `INSURANCE_FUND` - unfortunately this error appears rarely and can be after hours of working. I don't request at this time anything specific.
2. `INSURANCE_FUND` and `Blocking on _data_queue.put` - I'll definitely do it and if I'm not wrong it can be helpful for both cases - so I'll write as soon I have new logs.

**Comment by cjdsellers** [comment] 2023-07-27 10:10
Many thanks @Tzumx 

We're also working on improving the logging for networking, and are also continuing to improve the websocket client and setup.

**Comment by Tzumx** [comment] 2023-07-28 06:25
Great thanks!. I uncomment it and got some logs:
1. `INSURANCE_FUND` looks like sometime we got slight different websocket message - it rare case (this night I wait it for a 3 hours), but it happens:
```
2023-07-28T05:41:28.482138248Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"bchusdt@trade","data":{"e":"trade","E":1690522820463,"T":1690522820458,"s":"BCHUSDT","t":538575870,"p":"241.59","q":"0.056","X":"MARKET","m":true}}'
2023-07-28T05:41:28.482302601Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"btcusdt@trade","data":{"e":"trade","E":1690522820463,"T":1690522820458,"s":"BTCUSDT","t":3972156404,"p":"29216.90","q":"0.005","X":"INSURANCE_FUND","m":true}}'
2023-07-28T05:41:28.483453000Z [ERR] TRADER-001.DataClient-BINANCE: Error handling websocket message, Invalid enum value 'INSURANCE_FUND' - at `$.data.X`
...........

2023-07-28T05:41:28.927854075Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"ethusdt@trade","data":{"e":"trade","E":1690522820783,"T":1690522820777,"s":"ETHUSDT","t":3156929704,"p":"1833.17","q":"0.003","X":"INSURANCE_FUND","m":false}}'
2023-07-28T05:41:28.927927099Z [ERR] TRADER-001.DataClient-BINANCE: Error handling websocket message, Invalid enum value 'INSURANCE_FUND' - at `$.data.X`
```
more such logs in the attachment file
2. `_data_queue.put`
Not so clear.  It can appear at any moment, I didn't find (but cannot be sure of course) dependencies between this error and cpu load or some internal calculations.
```
2023-07-28T05:41:28.919319981Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"runeusdt@bookTicker","data":{"e":"bookTicker","u":3110080097900,"s":"RUNEUSDT","b":"0.9250","B":"8902","a":"0.9260","A":"26066","T":1690522820766,"E":1690522820771}}'
2023-07-28T05:41:28.919563155Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"nearusdt@bookTicker","data":{"e":"bookTicker","u":3110080098252,"s":"NEARUSDT","b":"1.3730","B":"3437","a":"1.3740","A":"19551","T":1690522820768,"E":1690522820773}}'
2023-07-28T05:41:28.919656190Z [WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.
2023-07-28T05:41:28.920325061Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"adausdt@bookTicker","data":{"e":"bookTicker","u":3110080098304,"s":"ADAUSDT","b":"0.30700","B":"120983","a":"0.30710","A":"5140","T":1690522820768,"E":1690522820773}}'
2023-07-28T05:41:28.920639276Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"adausdt@bookTicker","data":{"e":"bookTicker","u":3110080098647,"s":"ADAUSDT","b":"0.30700","B":"120584","a":"0.30710","A":"5140","T":1690522820771,"E":1690522820776}}'
2023-07-28T05:41:28.920772686Z [WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.
2023-07-28T05:41:28.921529794Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"avaxusdt@bookTicker","data":{"e":"bookTicker","u":3110080098684,"s":"AVAXUSDT","b":"13.1010","B":"359","a":"13.1020","A":"37","T":1690522820771,"E":1690522820776}}'
2023-07-28T05:41:28.922230652Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"roseusdt@bookTicker","data":{"e":"bookTicker","u":3110080098446,"s":"ROSEUSDT","b":"0.04953","B":"3017","a":"0.04955","A":"62975","T":1690522820769,"E":1690522820776}}'
2023-07-28T05:41:28.922849051Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"balusdt@bookTicker","data":{"e":"bookTicker","u":3110080098846,"s":"BALUSDT","b":"4.458","B":"169.5","a":"4.459","A":"98.6","T":1690522820772,"E":1690522820776}}'
2023-07-28T05:41:28.923045618Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"balusdt@bookTicker","data":{"e":"bookTicker","u":3110080099002,"s":"BALUSDT","b":"4.458","B":"125.8","a":"4.459","A":"98.6","T":1690522820773,"E":1690522820776}}'
2023-07-28T05:41:28.923133676Z [WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.
2023-07-28T05:41:28.923891415Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"solusdt@bookTicker","data":{"e":"bookTicker","u":3110080098681,"s":"SOLUSDT","b":"24.7050","B":"228","a":"24.7060","A":"54","T":1690522820771,"E":1690522820776}}'
2023-07-28T05:41:28.924122735Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"linkusdt@bookTicker","data":{"e":"bookTicker","u":3110080099051,"s":"LINKUSDT","b":"7.814","B":"1060.50","a":"7.815","A":"727.52","T":1690522820773,"E":1690522820777}}'
2023-07-28T05:41:28.924199561Z [WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.
2023-07-28T05:41:28.924282654Z [INF] TRADER-001.DataClient-BINANCE: b'{"stream":"bnbusdt@bookTicker","data":{"e":"bookTicker","u":3110080099329,"s":"BNBUSDT","b":"240.120","B":"36.94","a":"240.130","A":"81.64","T":1690522820774,"E":1690522820779}}'
2023-07-28T05:41:28.924335124Z [WRN] TRADER-001.DataEngine: Blocking on `_data_queue.put` as queue full at 10000 items.

```
More in attached file (1 minute of logs with both errors types)
[logs.zip](https://github.com/nautechsystems/nautilus_trader/files/12190843/logs.zip)

**Comment by cjdsellers** [comment] 2023-07-30 08:57
Hi @Tzumx 

I've added the `BinanceOrderType.INSURANCE_FUND`, pushed to `develop` branch and will be included in the next release - this should fix the first issue.

As for the blocking, the new default queue size is `100_000`, you could try setting `LiveDataEngineConfig.qsize` to this number:

```python
class LiveDataEngineConfig(DataEngineConfig, frozen=True):
    """
    Configuration for ``LiveDataEngine`` instances.

    Parameters
    ----------
    qsize : PositiveInt, default 100_000
        The queue size for the engines internal queue buffers.

    """

    qsize: PositiveInt = 100_000
```

You're not really subscribing to that many symbols so something must be holding up the event loop, is there any heavy computation in your strategy or actor handlers?

**Comment by Tzumx** [comment] 2023-07-30 15:22
Big thanks!! It's great news.

>  ...is there any heavy computation in your strategy or actor handlers?

There are some computation, but not heavy as I see, and they are happen on specific moment of time, but such error appear despite of calculations time that was confusion for me.

Thanks a lot to you, you are doing a really great job!

**Comment by Tzumx** [comment] 2023-08-08 11:26
Thanks again and small update from me.

I run the new version for a few days and:
1. No more INSURANCE_FUND issue
2. I almost was ready to write that no issue with blocking stuff, but yesterday it's happen again even with 100k queue. Really strange for me, because I was expected that such big queue size will be enough for any temporary blocking moments. But no... ((

**Comment by cjdsellers** [comment] 2023-08-09 09:39
Thanks for the update @Tzumx 

Good to hear point 1 has been addressed.

As for point 2, we need a more thorough investigation of the networking clients I think. 

We're currently working on an improved logger which will really help give some visibility into the Rust code, which will help on this issue.

**Comment by cjdsellers** [comment] 2023-08-13 02:31
Hi @Tzumx 

I've been making some improvements which has included removing the bespoke `Queue` implementation we were using for the live engines, replaced with the standard `asyncio.Queue` https://github.com/nautechsystems/nautilus_trader/commit/20afaa3b97e3fc803f1b51f6f061b8880bca2cc0.

I think this simplifies things, and _may_ improve the situation we're experiencing here, please report if you see further issues (or an improvement).

**Comment by cjdsellers** [comment] 2023-08-30 07:49
Hi @Tzumx 

Did you notice any improvement moving to the `asyncio.Queue` queues?

**Comment by cjdsellers** [comment] 2023-09-13 09:47
Closing this for now, as nothing is tangibly actionable.

We have not observed this occurring in our own trading, or seen a related/similar report from another user (one was similar but it turned out was due to blocking code in a strategy handler). Please report if you have anything further to report!

**Closed by cjdsellers** 2023-09-13 09:47 UTC
Labels: bug
