### ISSUE TITLE
Subscription for events.system

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1045] opened 2023-03-09 13:28 UTC
# Bug Report
While working to subscribe for ComponentState events, ended up with interesting bug. Upon bit diagnostic found that whenever `event.system.` have `ComponentId` in it the event is not delivered to Subscribers, however it does count in published events. However sending system event with any other pattern is delivered without any issue to subscribers. 

### Expected Behavior
Subscriber shall receive the ComponentState change messages.

### Actual Behavior
Subscriber doesn't receive the ComponentState change messages.

### Steps to Reproduce the Problem

1. Use file `tests/unit_tests/trading/test_trading_trader.py`
2. Add following test and run
```
    def test_msgbus_for_component_state(self):
        # Arrange
        subscriber = []
        strategy = Strategy(StrategyConfig(order_id_tag="001"))
        self.trader.add_strategy(strategy)
        strategy.msgbus.subscribe(topic="events.system.*", handler=subscriber.append)

        # Act
        self.trader.start()
        self.msgbus.publish("events.system.DUMMY", "DUMMY EVENT")
        self.msgbus.publish(f"events.system.{TestIdStubs.trader_id()}", "TRADER EVENT")

        # Assert
        assert self.msgbus.pub_count == 14
        assert len(subscriber) == 14  # <-- Not sure if all are events.system related, however I do expect two at minimum - but of two published only one gets delivered
```

### Specifications

- OS platform: Win10
- Python version: 3.10.6
- `nautilus_trader` version: develop-latest

**Comment by cjdsellers** [comment] 2023-03-11 02:48
I can confirm the behavior, and that it has something to do with the interaction of `ComponentId` with the wildcard `*`, but can't track it down yet. You can use a topic with exactly the same string literal as prints out from using the component ID, and it doesn't match in the above case as you've found.

By the way I noticed you're using Python 3.6?

**Comment by cjdsellers** [comment] 2023-03-11 02:52
Interestingly, the following test passes.

```python
    def test_msgbus_for_system_events_using_component_id(self):
        # Arrange
        subscriber = []
        self.msgbus.subscribe(topic=f"events.system.*", handler=subscriber.append)

        topic = f"events.system.{str(TestIdStubs.trader_id())}"

        # Act
        self.msgbus.publish("events.system.DUMMY", "DUMMY EVENT")
        self.msgbus.publish(topic, "TRADER EVENT")

        # Assert
        assert self.msgbus.pub_count == 2
        assert len(subscriber) == 2
```

**Comment by cjdsellers** [comment] 2023-03-11 02:57
I think you might find you've setup a test using two different message bus's.

**Comment by rsmb7z** [comment] 2023-03-11 14:46
Hi @cjdsellers 


> By the way I noticed you're using Python 3.6?

This was typo. Using 3.10.6


> I think you might find you've setup a test using two different message bus's.

If you do the same test in in `tests/unit_tests/trading/test_trading_trader.py` which comes more close the live usage, and it fails. Also the message bus is same in this case. Out of 2 messages only one gets delivered to subscriber - yes you are right though subscribing to specific `ComponentId` works. However wildcard will be more useful for Actor monitoring all the system events.

```
    def test_msgbus_for_system_events_using_component_id(self):
        # Arrange
        subscriber = []
        self.msgbus.subscribe(topic="events.system.*", handler=subscriber.append)

        topic = f"events.system.{str(TestIdStubs.trader_id())}"

        # Act
        self.msgbus.publish("events.system.DUMMY", "DUMMY EVENT")  # <-- this gets appended to `subscriber`
        self.msgbus.publish(topic, "TRADER EVENT")  # <-- this doesn't get appended to `subscriber` - this is the problem

        # Assert
        for msg in subscriber:
            print(msg)
```

**Comment by cjdsellers** [comment] 2023-03-12 02:02
I sunk a fair amount of time into this one yesterday, some things I determined:
- The pattern matching for the message bus works
- If you use exactly the same string literal as `topic` above, it works
- If you use _any_ identifier other than a `ComponentId` type, it works
- If you use a `ComponentId` and rely on the `__str__` for the `topic`, then it doesn't match (as outlined above), even though if you print the `topic` the string is the same as one which matches with wildcard as a straight literal

It truly is an odd one, and I don't have any other clues at this stage. I'll try to give it some more bandwidth next week unless you're able to keep digging? :pray:

**Comment by cjdsellers** [comment] 2023-03-18 21:46
So I updated the test and added an assert that the `subscriber` contains the expected events, which it does. Thoughts?

```
    def test_msgbus_for_system_events_using_component_id(self):
        # Arrange
        subscriber = []
        self.msgbus.subscribe(topic="events.system.*", handler=subscriber.append)

        topic = f"events.system.{str(TestIdStubs.trader_id())}"

        # Act
        self.msgbus.publish("events.system.DUMMY", "DUMMY EVENT")
        self.msgbus.publish(topic, "TRADER EVENT")

        # Assert
        assert self.msgbus.pub_count == 2
        assert len(subscriber) == 2
        assert subscriber == ["DUMMY EVENT", "TRADER EVENT"]
```

**Comment by cjdsellers** [comment] 2023-03-19 01:15
Closing this for now because I'm satisfied the message bus is working based on the above test. 

If you can reproduce the issue with another failing test, then I'm happy to reopen and continue the investigation :smile: .

**Closed by cjdsellers** 2023-03-19 01:15 UTC
Labels: bug

**Comment by rsmb7z** [comment] 2023-03-19 04:35
Hi,
I am here with the investation :boom:
It is something about matching and the hash being maintain, so for some reason it doesn't match and doesn't send the message to subscribers. Why not use the beutiful built-in RegEx which provides much more flexibility in matching patterns.

The working example is added [here](https://github.com/nautechsystems/nautilus_trader/commit/036d689436b5104fc8ec545f3b2393d48c0ba7cb).
`tests/unit_tests/trading/test_trading_trader.py/test_msgbus_for_system_events_using_component_id` would fail in current `develop` but works in proposed commit.
Only one test `test_unsubscribe_when_no_subscription_does_nothing` is failing with the change but not sure what exactly it is to do with 🙏

**Comment by cjdsellers** [comment] 2023-03-19 05:49
Thanks for looking into the alternative implementation using `re`, I tested it and unfortunately it runs at half the speed of the current implementation. I'd suggest maybe you could compile the regex which could improve the performance, it's definitely much cleaner though if we can bring the speed up. Also don't spend too much too because its a prime candidate for porting to Rust, and there's already an initial prototype for this in the codebase.

The weird thing is if you copy paste that exact test to `test_msgbus_bus.py` it passes on current develop. Which leads me to think its something about the setup fixture of the `test_trading_trader.py` module :thinking: .

**Comment by rsmb7z** [comment] 2023-03-19 10:58
> The weird thing is if you copy paste that exact test to `test_msgbus_bus.py` it passes on current develop. Which leads me to think its something about the setup fixture of the `test_trading_trader.py` module 🤔 .

For me this makes sense now. In the because `test_msgbus_bus.py` is pretty straight forwards and not too much events whereas in other case there are more events. As I was messing around, it is more of random match which causes it to halt processing. But in any case fixture is okay because it doesn't work in actual TradingNode as well.



> Thanks for looking into the alternative implementation using `re`, I tested it and unfortunately it runs at half the speed of the current implementation. I'd suggest maybe you could compile the regex which could improve the performance, it's definitely much cleaner though if we can bring the speed up. Also don't spend too much time, because the message bus is a prime candidate for porting to Rust, and there's already an initial prototype for this in the codebase.

Python does cache the compile I believe as per [this link](https://stackoverflow.com/questions/452104/is-it-worth-using-pythons-re-compile), but I will leave [this branch](https://github.com/nautechsystems/nautilus_trader/commit/4b901c9606d594f38c4c925bc1db1bc0e884ca19) for reference and can wait for it to be ported to Rust :relaxed:
