### ISSUE TITLE
Issue running on MacBook M1 (ARM64)

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#694] opened 2022-07-11 01:02 UTC
# Bug Report

### Expected Behavior
Run backtest example and see portfolio statistics and other readout.

### Actual Behavior
Segmentation error

### Steps to Reproduce the Problem
Use an M1 Mac - macOS Monterey
1. Install rust brew or rustup (tried both)
2.Install poetry
3.Install nautilus trader from source (see addition)
4.Run nautilus_trader/examples/backtest/crypto_ema_cross_ethusdt_trade_ticks.py

In addition: pip install -U nautilus_trader results in clang: error: nautilus_core/... not a file or directory

### Specifications

- OS platform: macOS Monterey
- Python version: 3.9-dev and 3.10
- `nautilus_trader` version: 1.148

```
(temp) ... python3 -q -X faulthandler
>>> from nautilus_trader.persistence.catalog import DataCatalog
Fatal Python error: Segmentation fault

Current thread 0x0000000100668580 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/nautilus_trader/nautilus_trader/persistence/catalog/base.py", line 25 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/nautilus_trader/nautilus_trader/persistence/catalog/__init__.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<stdin>", line 1 in <module>
```

**Comment by cjdsellers** [comment] 2022-07-16 07:14
I don't see the following line anywhere in the codebase:
```
from nautilus_trader.persistence.catalog import DataCatalog
```

We renamed to `ParquetDataCatalog`

I'll try a fresh build and run tests on my M1 now.

**Comment by cjdsellers** [comment] 2022-07-16 08:17
I'm also seeing the segfault running examples and tests on an M1.

I did a binary search of earlier commits and found that e51e1dcc0cbb57135415066d82c971ff9c756fd6 on 15/5/22 `Refine core Rust identifiers` was the one which broke it. 

Now trying to figure out why...

**Comment by cjdsellers** [comment] 2022-07-20 10:45
The build for macOS arm64 is now repaired and runs on my own MacBook M1.

The cause was an incorrectly configured Rust build for PyO3
https://pyo3.rs/master/building_and_distribution.html#macos

The fix involved some compiler flags for the platform target in the cargo config:
```
[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

And the addition of an `extension-module` PyO3 feature, to prevent it linking against the system Python.
```
pyo3 = { version = "^0.16.5", features = ["extension-module"] }
```

Closing this for now, please report any other specific issues for macOS arm64!

**Closed by cjdsellers** 2022-07-20 10:45 UTC
Labels: bug
