### ISSUE TITLE
Binance futures node cannot run when existing positions

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#1157] opened 2023-06-27 23:32 UTC
# Bug Report

### Expected Behavior
When exists positions,the node shold parsed it,so this could help continue running of straties.
### Actual Behavior
When exists positions,the node can not parse these positions and stopped,
Here is the log:
```
[1m2023-06-27T23:25:13.054882441Z[0m [94m[INF] TESTER-001.TradingNode: Awaiting execution state reconciliation (10.0s timeout)...[0m
[1m2023-06-27T23:25:13.054991434Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generating ExecutionMassStatus for BINANCE...[0m
[1m2023-06-27T23:25:13.055116208Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generating OrderStatusReports for BINANCE...[0m
[1m2023-06-27T23:25:13.055272453Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generating TradeReports for BINANCE...[0m
[1m2023-06-27T23:25:13.055339225Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generating PositionStatusReports for BINANCE...[0m
[1m2023-06-27T23:25:13.074635931Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generated 1 PositionStatusReport.[0m
[1m2023-06-27T23:25:13.087564244Z[0m [INF] TESTER-001.ExecClient-BINANCE: Generated 3 TradeReports.[0m
[1m2023-06-27T23:25:13.088300926Z[0m [1;31m[ERR] TESTER-001.ExecClient-BINANCE: Cannot reconcile execution state
ValueError(The 'quantity' was not a positive real, was 0.0)
Traceback (most recent call last):
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/execution_client.py", line 427, in generate_mass_status
    reports = await asyncio.gather(
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/adapters/binance/common/execution.py", line 402, in generate_order_status_reports
    report = order.parse_to_order_status_report(
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/adapters/binance/common/schemas/account.py", line 213, in parse_to_order_status_report
    return OrderStatusReport(
  File "nautilus_trader/execution/reports.pyx", line 178, in nautilus_trader.execution.reports.OrderStatusReport.__init__
  File "nautilus_trader/core/correctness.pyx", line 596, in nautilus_trader.core.correctness.Condition.positive
[0m
[1m2023-06-27T23:25:23.111386238Z[0m [1;33m[WRN] TESTER-001.TradingNode: Timed out (10.0s) waiting for node to stop.
Status
------
DataEngine.check_disconnected() == False
ExecEngine.check_disconnected() == False[0m


CancelledError()
Traceback (most recent call last):
  File "/home/ubuntu/live/twist_run.py", line 127, in <module>
    node.run()
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/node.py", line 267, in run
    self.kernel.loop.run_until_complete(self.run_async())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/node.py", line 387, in run_async
    await self.kernel.start()
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/system/kernel.py", line 724, in start
    if not await self._exec_engine.reconcile_state(
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/execution_engine.py", line 436, in reconcile_state
    result = self._reconcile_mass_status(mass_status)
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/execution_engine.py", line 499, in _reconcile_mass_status
    f"Reconciling ExecutionMassStatus for {mass_status.venue}.",
AttributeError: 'NoneType' object has no attribute 'venue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/node.py", line 346, in dispose
    self.kernel.cancel_all_tasks()
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/system/kernel.py", line 843, in cancel_all_tasks
    self.loop.run_until_complete(finish_all_tasks)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
[0m
[1m2023-06-27T23:25:23.113418010Z[0m [INF] TESTER-001.TradingNode: Closing event loop...[0m
[1m2023-06-27T23:25:23.113448821Z[0m [INF] TESTER-001.TradingNode: loop.is_running=False[0m
Traceback (most recent call last):
[1m2023-06-27T23:25:23.113450891Z[0m [INF] TESTER-001.TradingNode: loop.is_closed=True[0m
  File "/home/ubuntu/live/twist_run.py", line 127, in <module>
[1m2023-06-27T23:25:23.113451831Z[0m [INF] TESTER-001.TradingNode: DISPOSED.[0m
    node.run()
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/node.py", line 267, in run
    self.kernel.loop.run_until_complete(self.run_async())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/node.py", line 387, in run_async
    await self.kernel.start()
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/system/kernel.py", line 724, in start
    if not await self._exec_engine.reconcile_state(
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/execution_engine.py", line 436, in reconcile_state
    result = self._reconcile_mass_status(mass_status)
  File "/home/ubuntu/nautilus_trader-master/nautilus_trader/live/execution_engine.py", line 499, in _reconcile_mass_status
    f"Reconciling ExecutionMassStatus for {mass_status.venue}.",
AttributeError: 'NoneType' object has no attribute 'venue'

```
### Steps to Reproduce the Problem

1.open positions.
2.start any  binance live strategies.

### Specifications

- OS platform:Ubuntu22.04
- Python version: 10.0.8
- `nautilus_trader` version: latest mater version

**Comment by cjdsellers** [comment] 2023-06-28 09:37
Hi @graceyangfan 

Thanks for reporting this, so far I've tracked this down to the `origQty` being zero, which seems like a very strange value. Nautilus then validates this and considers it an invalid quantity.

During `parse_to_order_status_report`:
```
quantity=Quantity.from_str(self.origQty)
```

File "nautilus_trader/execution/reports.pyx", line 178
```
Condition.positive(quantity, "quantity")
```

I can't reproduce the scenario when I start with existing positions. Are you able to provide additional logs, or information on the scenario such as order types?

For the other open bug report (which is about to be fixed), the last part `AttributeError: 'NoneType' object has no attribute 'venue'` has been addressed.

**Comment by graceyangfan** [comment] 2023-06-28 12:22
@cjdsellers  strange parsed info  of orders：
```
the avg prx is 0.0000
the quantity is 1
 the order status is 6
the avg prx is 16.6930
the quantity is 1
 the order status is 12
the avg prx is 0.0000
the quantity is 0
 the order status is 6
```
while：
```
@unique
class BinanceOrderStatus(Enum):
    """Represents a `Binance` order status."""

    NEW = "NEW"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    PENDING_CANCEL = "PENDING_CANCEL"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    NEW_INSURANCE = "NEW_INSURANCE"  # Liquidation with Insurance Fund
    NEW_ADL = "NEW_ADL"  # Counterparty Liquidation
```
and info from binance:
```GET /fapi/v1/order => These orders will not be found:
order status is CANCELED or EXPIRED, AND
order has NO filled trade, AND
created time + 3 days < current time
```
I guess binance return some order with zero price and quantity which should be filtered before parse the order status.

**Comment by cjdsellers** [comment] 2023-06-29 09:59
Binance does make it hard to infer this from pure logic and requires extra knowledge of their API.

I just pushed a fix for this case to the `develop` branch, please let me know if this fixes things for you!

**Comment by cjdsellers** [comment] 2023-06-30 07:36
Hi @graceyangfan 

Did you get a chance to test again yet?

**Comment by graceyangfan** [comment] 2023-06-30 11:22
@cjdsellers it works now!

**Comment by cjdsellers** [comment] 2023-06-30 11:23
Great to hear! closing this then.

**Closed by cjdsellers** 2023-06-30 11:23 UTC
Labels: bug
