### ISSUE TITLE
Rounding error during Bar creation & aggregation creates invalid bars

### ISSUE THREAD

**Issue by dodofarm** [nautechsystems/nautilus_trader#2079] opened 2024-11-28 02:53 UTC
During internal bar aggregation there seems to be some rounding error during the backtest as can be seen below:

```
2024-10-28T16:00:00.000000000Z [INFO] BACKTESTER-001.RealStrengthStrategy: Bar instrument ID: XLE.XNAS-30-MINUTE-LAST-INTERNAL
2024-10-28T16:00:00.000000000Z [INFO] BACKTESTER-001.RealStrengthStrategy: Bar: XLE.XNAS
2024-10-28T16:00:00.000000000Z [INFO] BACKTESTER-001.RealStrengthStrategy: Bar close: 88.84 precision: 2
2024-10-28T16:01:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.84,88.86,88.84,88.84,1773,1730131200000000000)
2024-10-28T16:02:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.83,88.86,88.82,88.82,4047,1730131260000000000)
2024-10-28T16:03:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.81,88.81,88.78,88.79,1179,1730131320000000000)
2024-10-28T16:04:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.79,88.82,88.79,88.80,1504,1730131380000000000)
2024-10-28T16:05:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.80,88.83,88.80,88.83,3499,1730131440000000000)
2024-10-28T16:06:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.83,88.84,88.82,88.83,1478,1730131500000000000)
2024-10-28T16:07:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.82,88.84,88.82,88.83,689,1730131560000000000)
2024-10-28T16:08:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.83,88.86,88.82,88.86,806,1730131620000000000)
2024-10-28T16:09:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.86,88.89,88.85,88.89,1530,1730131680000000000)
2024-10-28T16:10:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.89,88.94,88.89,88.94,1228,1730131740000000000)
2024-10-28T16:11:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.94,88.94,88.92,88.94,2681,1730131800000000000)
2024-10-28T16:12:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.94,88.94,88.92,88.94,2553,1730131860000000000)
2024-10-28T16:13:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.94,88.99,88.94,88.99,1890,1730131920000000000)
2024-10-28T16:14:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.98,89.02,88.98,89.00,3905,1730131980000000000)
2024-10-28T16:15:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,88.99,88.97,88.97,692,1730132040000000000)
2024-10-28T16:16:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.96,89.01,88.95,89.01,1533,1730132100000000000)
2024-10-28T16:17:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.01,89.03,89.01,89.02,939,1730132160000000000)
2024-10-28T16:18:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.01,89.01,89.00,89.00,871,1730132220000000000)
2024-10-28T16:19:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,89.02,88.99,89.01,1085,1730132280000000000)
2024-10-28T16:20:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,88.99,88.95,88.96,2538,1730132340000000000)
2024-10-28T16:21:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.95,88.97,88.94,88.94,1204,1730132400000000000)
2024-10-28T16:22:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.95,89.00,88.95,89.00,1167,1730132460000000000)
2024-10-28T16:23:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,89.00,88.97,88.97,2427,1730132520000000000)
2024-10-28T16:24:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.98,89.00,88.98,89.00,714,1730132580000000000)
2024-10-28T16:25:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,88.99,88.99,88.99,350,1730132640000000000)
2024-10-28T16:26:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.00,89.02,89.00,89.02,1551,1730132700000000000)
2024-10-28T16:27:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.02,89.03,89.02,89.03,2112,1730132760000000000)
2024-10-28T16:28:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.03,89.03,88.98,88.99,2860,1730132820000000000)
2024-10-28T16:29:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.99,89.02,88.98,88.98,3852,1730132880000000000)
2024-10-28T16:30:00.000000000Z [DEBUG] BACKTESTER-001.OrderMatchingEngine(XNAS): Processing Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,88.98,89.03,88.98,89.03,1035,1730132940000000000)
2024-10-28T16:30:00.000000000Z [ERROR] BACKTESTER-001.BacktestNode: Error running backtest: high was < close, open: 88840000000, high: 89025000000, low: 88780000000, close: 89030000000, volume: 53692000000000, BarType:
 XLE.XNAS-30-MINUTE-LAST-INTERNAL
```

The actual error shows simply `high was < close` and the exception stems from [here](https://github.com/nautechsystems/nautilus_trader/blob/4bd9964d30e5eeb6cf987c99a4a63ce7b2cb83e7/nautilus_trader/model/data.pyx#L951). I added some more logging to show the actual values and for some reason `high` is `89025000000` even though from the bars above, the highest `high` is `89.03` which obviously shouldn't trigger this condition. 

Checking the raw data from databento we can see where the `89025` value that nautilus picked came from but not why the `89035` value which can be seen in the dataset is missing:

```
2024-10-28T15:59:00.000000000Z,33,2,17676,88.840000000,88.850000000,88.825000000,88.840000000,1531,XLE
2024-10-28T16:00:00.000000000Z,33,2,17676,88.840000000,88.855000000,88.840000000,88.840000000,1773,XLE
2024-10-28T16:01:00.000000000Z,33,2,17676,88.830000000,88.860000000,88.820000000,88.820000000,4047,XLE
2024-10-28T16:02:00.000000000Z,33,2,17676,88.815000000,88.815000000,88.780000000,88.790000000,1179,XLE
2024-10-28T16:03:00.000000000Z,33,2,17676,88.790000000,88.820000000,88.790000000,88.800000000,1504,XLE
2024-10-28T16:04:00.000000000Z,33,2,17676,88.800000000,88.830000000,88.795000000,88.830000000,3499,XLE
2024-10-28T16:05:00.000000000Z,33,2,17676,88.830000000,88.840000000,88.820000000,88.830000000,1478,XLE
2024-10-28T16:06:00.000000000Z,33,2,17676,88.820000000,88.840000000,88.820000000,88.830000000,689,XLE
2024-10-28T16:07:00.000000000Z,33,2,17676,88.830000000,88.855000000,88.820000000,88.855000000,806,XLE
2024-10-28T16:08:00.000000000Z,33,2,17676,88.860000000,88.890000000,88.850000000,88.890000000,1530,XLE
2024-10-28T16:09:00.000000000Z,33,2,17676,88.885000000,88.945000000,88.885000000,88.940000000,1228,XLE
2024-10-28T16:10:00.000000000Z,33,2,17676,88.935000000,88.940000000,88.915000000,88.940000000,2681,XLE
2024-10-28T16:11:00.000000000Z,33,2,17676,88.945000000,88.945000000,88.920000000,88.940000000,2553,XLE
2024-10-28T16:12:00.000000000Z,33,2,17676,88.940000000,88.990000000,88.940000000,88.990000000,1890,XLE
2024-10-28T16:13:00.000000000Z,33,2,17676,88.985000000,89.015000000,88.985000000,89.000000000,3905,XLE
2024-10-28T16:14:00.000000000Z,33,2,17676,88.990000000,88.990000000,88.970000000,88.970000000,692,XLE
2024-10-28T16:15:00.000000000Z,33,2,17676,88.960000000,89.010000000,88.950000000,89.010000000,1533,XLE
2024-10-28T16:16:00.000000000Z,33,2,17676,89.010000000,89.025000000,89.010000000,89.015000000,939,XLE
2024-10-28T16:17:00.000000000Z,33,2,17676,89.010000000,89.010000000,88.995000000,88.995000000,871,XLE
2024-10-28T16:18:00.000000000Z,33,2,17676,88.990000000,89.015000000,88.990000000,89.010000000,1085,XLE
2024-10-28T16:19:00.000000000Z,33,2,17676,88.990000000,88.990000000,88.955000000,88.960000000,2538,XLE
2024-10-28T16:20:00.000000000Z,33,2,17676,88.955000000,88.965000000,88.945000000,88.945000000,1204,XLE
2024-10-28T16:21:00.000000000Z,33,2,17676,88.950000000,89.000000000,88.950000000,89.000000000,1167,XLE
2024-10-28T16:22:00.000000000Z,33,2,17676,88.990000000,88.995000000,88.965000000,88.970000000,2427,XLE
2024-10-28T16:23:00.000000000Z,33,2,17676,88.980000000,89.005000000,88.980000000,88.995000000,714,XLE
2024-10-28T16:24:00.000000000Z,33,2,17676,88.990000000,88.990000000,88.990000000,88.990000000,350,XLE
2024-10-28T16:25:00.000000000Z,33,2,17676,89.000000000,89.015000000,89.000000000,89.015000000,1551,XLE
2024-10-28T16:26:00.000000000Z,33,2,17676,89.020000000,89.035000000,89.015000000,89.035000000,2112,XLE
2024-10-28T16:27:00.000000000Z,33,2,17676,89.035000000,89.035000000,88.980000000,88.990000000,2860,XLE
2024-10-28T16:28:00.000000000Z,33,2,17676,88.990000000,89.020000000,88.985000000,88.985000000,3852,XLE
2024-10-28T16:29:00.000000000Z,33,2,17676,88.985000000,89.030000000,88.980000000,89.030000000,1035,XLE
```

You can see the open, low & close are correct in nautilus but the correct high value is missing for some reason. Additionally some values are just rounded incorrectly, for example this candle in the databento data:

2024-10-28T16:26:00.000000000Z,33,2,17676,89.020000000,89.035000000,89.015000000,89.035000000,2112,XLE

is this candle in the catalog (confirmed by same volume value):
Bar(XLE.XNAS-1-MINUTE-LAST-EXTERNAL,89.02,89.03,89.02,89.03,2112,1730132760000000000),

the values are simply rounded incorrectly at some places it seems. 

### Steps to Reproduce the Problem
1. I used 1 minute XLE data from databento and aggregated for the backtest like this: `f"{XLE_XNAS.id}-30-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL"`
2. then simply run any strategy and you should see the error, I ran the example EmaCross strategy (without the `request_bars` code since it would request the wrong aggregated `bar_type`) with the below config:
```python
strategies = [
    ImportableStrategyConfig(
        strategy_path="nautilus_trader.examples.strategies.ema_cross:EMACrossWithoutRequestBars",
        config_path="nautilus_trader.examples.strategies.ema_cross:EMACrossWithoutRequestBarsConfig",
        config={
            "instrument_id": XLE_XNAS.id,
            "bar_type": BarType.from_str(
                f"{XLE_XNAS.id}-30-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL"
            ),
            "trade_size": Decimal("1.000"),
            "fast_ema_period": 10,
            "slow_ema_period": 20,
        },
    ),
]
```

weirdly, using hourly bars works fine on the data from the 28th of October but fails shortly after on the 30th of October but this time with `low was > close`  which is basically the same issue. I suppose there's some sort of issue where values with higher precision than 2 are sometimes rounded incorrectly when creating EXTERNAL Bars and/or not picked up when creating new INTERNAL aggregated Bar objects which causes the aggregated Bar `high` in the bar to not be the actual `high` in the data. The `89025000000` is coming from the catalog itself which I confirmed by inspecting the actual parquet file.

I've tried setting the price precision higher like this:
```python
XLE_XNAS = Equity(
    instrument_id=InstrumentId(symbol=Symbol("XLE"), venue=Venue("XNAS")),
    raw_symbol=Symbol("XLE"),
    currency=USD,
    price_precision=5,
    price_increment=Price.from_str("0.00001"),
    lot_size=Quantity.from_int(100),
    isin="US0378331005",
    ts_event=0,
    ts_init=0,
)

loader = DatabentoDataLoader()

xle_bars = loader.from_dbn_file(
    path=path / "xle.xnas.ohlcv-1m.dbn.zst",
    instrument_id=XLE_XNAS.id,  # instrument_id,
    as_legacy_cython=False,  # This is an optimization for writing to the catalog
)
catalog = ParquetDataCatalog(CATALOG_DIR)
```

but that didn't change the bars generated and used in the backtest, they were exactly the same as above as far as I could tell.

#### So in the end I have two questions:
 - why are the bars rounded incorrectly? Is this because of the wrong price precision or something similar?
 - How can I increase the price precision so that the value used in the generated bar is the same as in the raw data

### Specifications

- OS platform: Amazon Linux
- Python version: 3.12.7
- `nautilus_trader` version: latest develop [commit ](https://github.com/nautechsystems/nautilus_trader/commit/ed262521f08d508f0d056e86637f92dedb0d54f3)

**Comment by cjdsellers** [comment] 2024-11-28 07:46
Hi @dodofarm

Thanks for reaching out, and for providing all that detail!

The reason why we're rounding incorrectly is because the quote currency is currently hard coded as USD in the Nautilus decoder:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/adapters/src/databento/decode.rs#L939

If the `precision` being used with `decode_price` was changed to 3, then this would _probably_ work. You could actually try this and recompile, as you're working from `develop` branch.

Looking at the instrument definitions around that period, the `currency` field isn't populated. The instrument appears to be quoting on Nasdaq in USD, so not sure why we'd be seeing bars that require a precision of 3 to avoid the rounding errors.

The `min_price_increment` field also isn't populated, so on first pass I'm not sure how we can determine what the correct precision actually should be? (do you have any thoughts here?)

The fix will probably involve being able to specify a different precision than 2 for USD, but I would have to look more thoroughly on where we could thread that through into the decoder.

**Comment by cjdsellers** [comment] 2024-11-29 00:36
Per [discussions on Discord](https://discord.com/channels/924497682343550976/1192961049293508673/1311599077749690400):

Added a `price_precision` optional parameter for `DatabentoDataLoader` methods to cater for situations where the price precision is different to the expected precision for the quote currency (typically USD for the datasets currently available).

Closing for now pending a root cause investigation as to why the precision is different than expected.

@dodofarm feel free to continue the conversation in this issue though, or is anyone else has any input.

**Closed by cjdsellers** 2024-11-29 00:36 UTC
Labels: bug
